/* Creates a standalone, fully offline HTML from the editable Vue application. */
const fs=require('node:fs');
const mapCountries=JSON.parse(fs.readFileSync('assets/map-countries.geojson','utf8'));
const mapPlaces=JSON.parse(fs.readFileSync('assets/map-places.geojson','utf8'));
fs.writeFileSync('assets/map-places.js','globalThis.MasalMapPlaces='+JSON.stringify({type:'FeatureCollection',features:mapPlaces.features.map(f=>({type:'Feature',properties:{name:f.properties.NAME_AR||f.properties.NAME},geometry:f.geometry}))})+';');
fs.writeFileSync('assets/map-countries.js','globalThis.MasalMapCountries='+JSON.stringify({type:'FeatureCollection',features:mapCountries.features.map(f=>({type:'Feature',properties:{name:f.properties.NAME_AR||f.properties.NAME,id:f.properties.ADM0_A3},geometry:f.geometry}))})+';');
fs.writeFileSync('company-public-runtime.js','globalThis.MasalCompanyVueSource='+JSON.stringify(fs.readFileSync('assets/vue.global.prod.js','utf8'))+';');
let html=fs.readFileSync('index.html','utf8');
html=html.replace('<link rel="stylesheet" href="support-chat.css">','<style>'+fs.readFileSync('support-chat.css','utf8')+'</style>');
html=html.replace('<link rel="stylesheet" href="agent-products.css">','<style>'+fs.readFileSync('agent-products.css','utf8')+'</style>');
html=html.replace('<link rel="stylesheet" href="network-tree.css">','');
html=html.replace('<link rel="stylesheet" href="operations.css">','');
html=html.replace('<link rel="stylesheet" href="reference-identity.css">','');
html=html.replace('<link rel="stylesheet" href="company-profile.css">','');
html=html.replace('<link rel="stylesheet" href="assets/leaflet.css">','');let css=fs.readFileSync('assets/leaflet.css','utf8')+'\n'+fs.readFileSync('styles.css','utf8')+'\n'+fs.readFileSync('operations.css','utf8')+'\n'+fs.readFileSync('theme.css','utf8')+'\n'+fs.readFileSync('layout.css','utf8')+'\n'+fs.readFileSync('polish.css','utf8')+'\n'+fs.readFileSync('management.css','utf8')+'\n'+fs.readFileSync('network-tree.css','utf8')+'\n'+fs.readFileSync('reference-identity.css','utf8')+'\n'+fs.readFileSync('company-profile.css','utf8');
html=html.replace('<link rel="stylesheet" href="management.css">','');
html=html.replace('<link rel="stylesheet" href="theme.css">','').replace('<link rel="stylesheet" href="layout.css">','').replace('<link rel="stylesheet" href="polish.css">','');
for(const file of ['cairo-regular.ttf','cairo-bold.ttf','cairo-black.ttf','jetbrains-mono.ttf'])css=css.replaceAll('assets/'+file,'data:font/ttf;base64,'+fs.readFileSync('assets/'+file).toString('base64'));
html=html.replace('<link rel="stylesheet" href="styles.css">','<style>'+css+'</style>');
for(const file of ['assets/leaflet.js','assets/map-countries.js','assets/map-places.js','assets/vue.global.prod.js','access.js','card-fields.js','engine.js','operations-engine.js','import-reader.js','operations-ui.js','workflow-engine.js','workflow-ui.js','completion-engine.js','completion-ui.js','locales.js','management-locales.js','operations-locales.js','completion-locales.js','reports.js','enhancements.js','staff-model.js','staff-ui.js','network-tree.js','audit-details.js','network-accounts.js','support-routing.js','simple-notifications.js','form-lifecycle.js','login-screen.js','visual-cleanup.js','excel-export.js','feature-updates.js','dashboard.js','meeting-rules.js','meeting-ui.js','categories-ui.js','regions.js','company-public-runtime.js','company-site.js','card-layout.js','providers-ui.js','inventory-ui.js','wallet-filters.js','searchable-selects.js','cash-orders.js','table-pagination.js','seller-accounts.js','print-escalation.js','funding-rules.js','audit-fixes.js','report-groups.js','scope-filters.js','money-inputs.js','security-controls.js','simple-wallets.js','activity-notifications.js','print-policies.js','print-policy-scopes.js','print-scope-picker.js','account-time-controls.js','support-broadcast.js','user-map.js','price-editor.js','agent-products.js','daily-print.js','support-chat.js','network-archive.js','password-admin.js','pos-register.js','order-sources.js','order-parser.js','multi-orders.js','inventory-management.js','ui-localization.js','app.js']){const source=fs.readFileSync(file,'utf8').replace(/<\/script/gi,'<\\/script');html=html.replace('<script src="'+file+'"></script>',()=>'<script>'+source+'</script>');}
fs.writeFileSync('masal.html',html,'utf8');console.log('Built standalone masal.html ('+Math.round(Buffer.byteLength(html)/1024)+' KB)');
