(function(root){
'use strict';
function resolve(s,id,agent={},override){const p=s.products.find(x=>x.id===id)||{},provider=s.providers.find(x=>x.id===p.provider)||{};const inherited=p.designSource==='provider';const legacy=(p.receiptHeader||p.receiptFooter||p.receiptImage||p.receiptWidth)?{...(provider.cardDesign||{}),header:p.receiptHeader??provider.cardDesign?.header,footer:p.receiptFooter??provider.cardDesign?.footer,width:p.receiptWidth||provider.cardDesign?.width,image:p.receiptImage??provider.cardDesign?.image}:null;const d=override||(!inherited&&(p.cardDesign||legacy))||provider.cardDesign||{};return {color:d.color||'#172b4d',width:d.width||(!inherited&&p.receiptWidth)||agent.width||80,header:d.header??(!inherited?p.receiptHeader:'')??'',footer:d.footer??(!inherited?p.receiptFooter:'')??'',image:d.image||p.image||(!inherited&&p.receiptImage)||provider.cardDesign?.image||provider.receiptImage||provider.image||provider.logo||'',order:d.order||MasalMeetingRules.blocks}}
Masal.Engine.prototype.inheritCompanyDesign=function(id){this.requirePermission('branding.receipt');this.requirePermission('products.edit');const p=this.s.products.find(x=>x.id===id);if(!p)throw Error('اختر الفئة');p.designSource='provider';this.log('استخدام قالب الشركة',id,null,{provider:p.provider})};
const saveDesign=Masal.Engine.prototype.saveCardDesign;
Masal.Engine.prototype.saveCardDesign=function(type,id,draft){const result=saveDesign.call(this,type,id,draft);if(type==='product'){const p=this.s.products.find(x=>x.id===id);p.designSource='product';Object.assign(p,{receiptWidth:p.cardDesign.width,receiptHeader:p.cardDesign.header,receiptFooter:p.cardDesign.footer,receiptImage:p.cardDesign.image})}return result};
function install(o){
 const data=o.data;o.data=function(){return {...data.call(this),brandingTab:'template',brandPreviewProduct:''}};
 const receipt=o.components['meeting-receipt'];receipt.props.push('agentOverride');
 receipt.computed.agent=function(){return this.agentOverride||this.vm.s.agents.find(a=>a.id===this.vm.engine.main(this.tx?.agent||this.vm.brandAgent))||{}};
 receipt.computed.image=function(){return this.layout.image||this.product.image||this.provider.receiptImage||''};
 receipt.computed.layout=function(){return resolve(this.vm.s,this.product.id,this.agent,this.design)};
 receipt.template=receipt.template.replace('<img v-if="provider.logo||agent.logo" :src="provider.logo||agent.logo" class="receipt-logo">','<div class="receipt-identities"><img v-if="provider.logo" :src="provider.logo" :alt="provider.name" class="receipt-logo"><img v-if="agent.logo&&agent.logo!==provider.logo" :src="agent.logo" :alt="agent.name" class="receipt-logo"></div>');
 receipt.template=receipt.template.replace('<div>{{layout.header}}</div>','<div>{{layout.header}}</div><div v-if="agent.header&&agent.header!==layout.header">{{agent.header}}</div>');
 receipt.template=receipt.template.replace('<div>{{layout.footer}}</div>','<div>{{layout.footer}}</div><div v-if="agent.footer&&agent.footer!==layout.footer">{{agent.footer}}</div>');
 const designer=o.components['card-designer'],dd=designer.data;designer.data=function(){return {...dd.call(this),inherit:false,imageBusy:false}};
 designer.methods.load=function(){const item=this.items.find(x=>x.id===this.selected);this.inherit=this.type==='product'&&(item?.designSource==='provider'||(!item?.cardDesign&&!item?.receiptHeader&&!item?.receiptFooter&&!item?.receiptImage&&!item?.receiptWidth));this.previewProduct=this.type==='product'?this.selected:this.vm.s.products.find(p=>p.provider===this.selected)?.id||'';this.draft=Masal.clone(this.type==='product'?resolve(this.vm.s,this.selected):item?.cardDesign||{color:'#172b4d',width:80,header:'',footer:'',image:'',order:MasalMeetingRules.blocks})};
 designer.methods.save=function(){if(this.imageBusy)return;this.vm.run(()=>{if(this.type==='product'&&this.inherit)this.vm.engine.inheritCompanyDesign(this.selected);else this.vm.engine.saveCardDesign(this.type,this.selected,this.draft);this.load()},'تم حفظ قالب البطاقة')};
 designer.watch['vm.page']=function(page){if(page==='branding')this.load()};
 designer.watch.inherit=function(inherit){if(inherit&&this.type==='product'){const p=this.items.find(x=>x.id===this.selected),provider=this.vm.s.providers.find(x=>x.id===p?.provider);this.draft=Masal.clone(provider?.cardDesign||{color:'#172b4d',width:80,header:'',footer:'',image:'',order:MasalMeetingRules.blocks})}};
 designer.template=designer.template.replace("vm.page==='branding'&&draft", "vm.page==='branding'&&vm.brandingTab==='template'&&draft").replace('<label>التصميم<select','<label>القالب المطلوب<select').replace('<label>الترويسة','<label>النص أعلى البطاقة').replace('<label>التذييل','<label>النص أسفل البطاقة');
 designer.template=designer.template.replace('<label>اللون<input', '</div><label v-if="type===\'product\'" class="inline-check"><input type="checkbox" v-model="inherit">استخدام قالب الشركة</label><fieldset class="card-design-fields" :disabled="inherit&&type===\'product\'"><div class="formgrid"><label>اللون<input');
 designer.template=designer.template.replace('<image-attachment v-model="draft.image"></image-attachment>','<image-attachment :key="[type,selected,inherit].join()" v-model="draft.image" @busy="imageBusy=$event"></image-attachment>');
 designer.template=designer.template.replace('<button class="btn primary">حفظ</button>','</fieldset><button class="btn primary" :disabled="imageBusy">حفظ</button>');
 designer.methods.preview=function(){if(this.imageBusy)return;this.vm.previewCardDesign(this.previewProduct,this.draft)};
 designer.template=designer.template.replace('</fieldset><button class="btn primary"', '</fieldset><div class="formfoot"><button type="button" class="btn" :disabled="imageBusy||!previewProduct" @click="preview">معاينة</button><button class="btn primary"').replace('>حفظ</button></form>','>حفظ</button></div></form>');
 o.methods.previewCardDesign=function(productId,design,agentDraft){this.run(()=>{this.engine.requirePermission('branding.view');if(!this.s.products.some(p=>p.id===productId))throw Error('اختر فئة للمعاينة');const a=agentDraft||this.s.agents.find(x=>x.id===this.brandAgent)||{};this.modal={kind:'cardDesignPreview',title:'معاينة البطاقة',productId,design:Masal.clone(design||resolve(this.s,productId,a)),agent:Masal.clone(a)}})};
 o.components['branding-switcher']={computed:{vm(){return this.$root}},template:`<div v-if="vm.page==='branding'" class="tabs branding-tabs"><button v-if="vm.can('branding.receipt')&&(vm.can('products.edit')||vm.can('providers.edit'))" :class="{active:vm.brandingTab==='template'}" @click="vm.brandingTab='template'">قالب البطاقة</button><button v-if="vm.can('branding.edit')" :class="{active:vm.brandingTab==='agent'}" @click="vm.brandingTab='agent'">بيانات الوكيل</button></div>`};
 const go=o.methods.go;o.methods.go=function(page){const r=go.call(this,page);if(page==='branding'&&this.page===page){this.brandingTab=this.can('branding.edit')?'agent':'template';if(!this.visibleAgents.some(a=>a.id===this.brandAgent&&a.type==='رئيسي'))this.brandAgent=this.visibleAgents.find(a=>a.type==='رئيسي')?.id||'';this.loadBrand();this.brandPreviewProduct=this.brandingProducts[0]?.id||''}return r};
 const agent=o.computed.receiptAgent;o.computed.receiptAgent=function(){const a=agent.call(this);const source=this.s.agents.find(x=>x.id===this.engine.main(this.modal?.tx?.agent))||{};return {...a,width:resolve(this.s,this.modal?.tx?.product,source).width}};
 const save=o.methods.saveEntity;o.methods.saveEntity=function(){if(this.page==='products'){const p=this.editForm,old=this.s.products.find(x=>x.id===p.id),keys=['receiptHeader','receiptFooter','receiptWidth','receiptImage'];if((!old&&(p.receiptHeader||p.receiptFooter||p.receiptImage||p.receiptWidth!==80))||(old&&(p._loadedReceipt?JSON.stringify([p.receiptHeader,p.receiptFooter,p.receiptWidth,p.receiptImage])!==p._loadedReceipt:keys.some(k=>p[k]!==old[k])))){const d=resolve(this.s,p.id);p.cardDesign={...Masal.clone(d),header:p.receiptHeader||'',footer:p.receiptFooter||'',width:Number(p.receiptWidth)||80,image:p.receiptImage||''};p.designSource='product'}delete p._loadedReceipt}return save.call(this)};
 const open=o.methods.openEdit;o.methods.openEdit=function(row){open.call(this,row);if(this.page==='products'&&row){const d=resolve(this.s,row.id);Object.assign(this.editForm,{receiptHeader:d.header,receiptFooter:d.footer,receiptWidth:d.width,receiptImage:d.image});this.editForm._loadedReceipt=JSON.stringify([d.header,d.footer,d.width,d.image])}};
 // Keep the saved order and artwork; expose only the everyday editing fields.
 o.computed.brandingProducts=function(){return this.s.products.filter(p=>(!this.engine.catalogProductVisible||this.engine.catalogProductVisible(p.id))&&(!this.brandAgent||this.engine.agentProductAllowed(this.brandAgent,p.id)))};
 designer.computed.items=function(){return this.type==='product'?this.vm.s.products.filter(p=>!this.vm.engine.catalogProductVisible||this.vm.engine.catalogProductVisible(p.id)):this.vm.s.providers};
 const simpleLoad=designer.methods.load;designer.methods.load=function(){if(this.type==='product'&&!this.vm.can('products.edit')&&this.vm.can('providers.edit'))this.type='provider';if(!this.items.some(x=>x.id===this.selected))this.selected=this.items[0]?.id||'';simpleLoad.call(this);const item=this.items.find(x=>x.id===this.selected);if(this.draft&&!item?.cardDesign?.image&&!item?.receiptImage)this.draft.image=''};
 designer.methods.save=function(){this.vm.run(()=>{this.vm.engine.saveCardDesign(this.type,this.selected,this.draft);this.load()},'تم حفظ تصميم البطاقة')};
 designer.methods.restore=function(){this.vm.run(()=>{this.vm.engine.inheritCompanyDesign(this.selected);this.load()},'تم استخدام قالب الشركة')};
 designer.template=`<div v-if="vm.page==='branding'&&vm.brandingTab==='template'&&draft&&vm.can('branding.receipt')&&(vm.can('products.edit')||vm.can('providers.edit'))" class="two simple-card-designer"><form class="card" @submit.prevent="save"><div class="formgrid"><label>تعديل قالب<select v-model="type"><option v-if="vm.can('products.edit')" value="product">فئة</option><option v-if="vm.can('providers.edit')" value="provider">شركة</option></select></label><label>{{type==='product'?'الفئة':'الشركة'}}<select v-model="selected"><option v-for="item in items" :value="item.id">{{item.name}}</option></select></label><label class="full">النص أعلى البطاقة<input v-model="draft.header" aria-label="نص القالب أعلى البطاقة"></label><label class="full">النص أسفل البطاقة<input v-model="draft.footer" aria-label="نص القالب أسفل البطاقة"></label><label>لون النص<input type="color" v-model="draft.color"></label><label>عرض الورق<select v-model.number="draft.width"><option :value="58">58 ملم</option><option :value="80">80 ملم</option></select></label></div><div class="formfoot"><button v-if="type==='product'" type="button" class="btn" @click="restore">استخدام قالب الشركة</button><button class="btn primary" :disabled="!selected">حفظ التصميم</button></div></form><div class="card simple-card-preview"><h3>معاينة مباشرة</h3><meeting-receipt v-if="previewProduct" :design="draft" :product-id="previewProduct"></meeting-receipt><template v-else><img v-if="items.find(x=>x.id===selected)?.logo||items.find(x=>x.id===selected)?.image" class="simple-company-image" :src="items.find(x=>x.id===selected)?.image||items.find(x=>x.id===selected)?.logo" alt="صورة الشركة"><p>{{draft.header}}</p><p>{{draft.footer}}</p></template></div></div>`;
}
root.MasalCardLayout={resolve,install};
})(globalThis);
