(function(root){
'use strict';
const M=root.Masal,P=M.Engine.prototype,copy=M.clone;
const baseBalance=P.serviceBalance,baseAvailable=P.serviceAvailable,baseRequest=P.requestFunding,baseReserve=P.reserveFunding;
function serviceIds(engine){return ['voucher','topup','cash',...engine.s.providers.filter(p=>p.connection==='API').map(p=>'api:'+p.id)]}
function assertService(engine,service){if(service==='all')throw Error('اختر خدمة محددة للتمويل؛ الإجمالي للعرض فقط')}
function rollback(state,before){for(const key of Object.keys(state))if(!(key in before))delete state[key];Object.assign(state,before)}
function atomic(engine,fn){const before=copy(engine.s);try{return fn()}catch(error){rollback(engine.s,before);throw error}}
function controller(engine){const user=engine.actor();return user?.staffAccount&&user.staffAccount!=='@system'?user.staffAccount:user?.agent||''}
function assertOwner(engine,from){if(controller(engine)!==from)throw Error('التمويل ينفذه مستخدم مخوّل من حساب الوكيل المموّل فقط')}
P.serviceBalance=function(account,service='voucher'){return service==='all'?serviceIds(this).reduce((sum,id)=>sum+baseBalance.call(this,account,id),0):baseBalance.call(this,account,service)};
P.serviceAvailable=function(account,service='voucher'){return service==='all'?serviceIds(this).reduce((sum,id)=>sum+baseAvailable.call(this,account,id),0):baseAvailable.call(this,account,service)};
const baseFund=P.fund;
P.fund=function(from,to,amount,service,key){assertService(this,service);assertOwner(this,from);return baseFund.call(this,from,to,amount,service,key,'')};
P.requestFunding=function(to,from,amount,service,purpose,key){assertService(this,service);return baseRequest.call(this,to,from,amount,service,purpose,key)};
P.authorizeFunding=function(){throw Error('تم إلغاء التمويل الاستثنائي؛ التمويل ينفذه حساب الوكيل فقط')};
P.reserveFunding=function(id,amount){const request=this.s.fundingRequests.find(r=>r.id===id);if(!request)throw Error('الطلب غير موجود');assertService(this,request.service);assertOwner(this,request.from);return baseReserve.call(this,id,amount,'')};
P.bulkFunding=function(rows,service,key){this.operations();this.requirePermission('wallets.bulk');this.requirePermission('wallets.transfer');assertService(this,service);if(!key)throw Error('معرف المجموعة مطلوب');if(!Array.isArray(rows)||!rows.length)throw Error('أدخل مستفيدًا ومبلغًا لكل سطر');const from=rows[0]?.from;assertOwner(this,from);if(rows.some(r=>r.from!==from))throw Error('كل مستفيدي المجموعة يجب أن يكونوا من الوكيل نفسه');if(new Set(rows.map(r=>r.to)).size!==rows.length)throw Error('المستفيد مكرر في المجموعة');const total=rows.reduce((sum,r)=>sum+Number(r.amount),0);if(!Number.isFinite(total)||rows.some(r=>!Number.isFinite(Number(r.amount))||Number(r.amount)<=0))throw Error('تحقق من مبالغ المجموعة');if(this.serviceAvailable(from,service)<total)throw Error('رصيد الوكيل لا يكفي لكامل المجموعة؛ لم ينفذ أي تمويل');const previous=this.s.fundingTransfers.filter(t=>t.groupKey===key);if(previous.length===rows.length)return rows.map(r=>({to:r.to,status:'منفذ',transfer:previous.find(t=>t.to===r.to)?.id}));if(previous.length)throw Error('هذه المجموعة غير مكتملة؛ استخدم مفتاح مجموعة جديد');return atomic(this,()=>rows.map((r,i)=>{const t=this.fund(from,r.to,r.amount,service,key+'-'+i);t.groupKey=key;return {to:r.to,status:'منفذ',transfer:t.id}}))};
P.processFundingBatch=function(ids,amounts={}){this.operations();this.requirePermission('wallets.approve');const requests=ids.map(id=>this.s.fundingRequests.find(r=>r.id===id));if(!requests.length||requests.some(r=>!r||r.status!=='بانتظار التمويل'))throw Error('حدد طلبات تمويل بانتظار المعالجة فقط');const from=requests[0].from,service=requests[0].service;assertService(this,service);assertOwner(this,from);if(requests.some(r=>r.from!==from||r.service!==service))throw Error('اعتمد معًا طلبات الوكيل والخدمة نفسيهما فقط');const values=requests.map(r=>Number(amounts[r.id]??r.amount));if(values.some(v=>!Number.isFinite(v)||v<=0))throw Error('تحقق من مبالغ الطلبات');if(this.serviceAvailable(from,service)<values.reduce((n,v)=>n+v,0))throw Error('رصيد الوكيل لا يكفي لكل الطلبات؛ لم ينفذ أي طلب');return atomic(this,()=>requests.map((r,index)=>this.processFunding(r.id,values[index])))};
function install(o){const panel=o.components['operations-panel'],baseServices=panel.computed.services,baseLedger=panel.computed.ledger,baseServiceName=panel.methods.serviceName;panel.computed.services=function(){return [{id:'all',name:'إجمالي كل الأرصدة'},...baseServices.call(this)]};panel.computed.ledger=function(){if(this.service!=='all')return baseLedger.call(this);return this.s.serviceLedger.filter(l=>this.accounts.some(a=>a.id===l.account)&&(!this.account||l.account===this.account)).slice().reverse()};panel.computed.balanceTotal=function(){const accounts=this.walletAccounts||this.accounts;if(this.service!=='all')return accounts.reduce((n,a)=>n+this.e.serviceBalance(a.id,this.service),0);const ids=this.services.filter(s=>s.id!=='all').map(s=>s.id);return accounts.reduce((sum,a)=>sum+ids.reduce((n,id)=>n+this.e.serviceBalance(a.id,id),0),0)};panel.methods.serviceName=function(id){return id==='all'?'إجمالي كل الأرصدة':baseServiceName.call(this,id)};panel.methods.approveRequests=function(){this.act(()=>{const result=this.e.processFundingBatch(this.fundSelected,this.fundAmounts);this.fundSelected=[];this.fundAmounts={};return result},'تم تنفيذ الطلبات المحددة دفعة واحدة')}}
const cents=value=>Math.round(Number(value)*100);
P.recoverableFunding=function(from,to,service){this.operations();const remaining=this.s.fundingTransfers.filter(t=>t.from===from&&t.to===to&&t.service===service&&t.status!=='معكوس').reduce((sum,t)=>sum+Math.max(0,cents(t.amount)-cents(t.recoveredAmount||0)),0);return Math.max(0,Math.min(remaining,cents(this.serviceAvailable(to,service))))/100};
P.recoverFunding=function(from,to,amount,service,reason,key){
 this.operations();this.requirePermission('wallets.reverse');assertOwner(this,from);assertService(this,service);this.accountCheck(from);this.accountCheck(to);
 if(from===to||!this.descendants(from).includes(this.accountAgent(to)))throw Error('الاسترجاع من الحسابات التابعة للوكيل فقط');
 amount=Number(amount);reason=String(reason||'').trim();if(!Number.isFinite(amount)||amount<=0||Math.abs(amount*100-cents(amount))>0.00001)throw Error('أدخل مبلغًا موجبًا بمنزلتين عشريتين كحد أقصى');if(!reason||!key)throw Error('سبب الاسترجاع مطلوب');
 const old=(this.s.fundingRecoveries||[]).find(r=>r.key===key);if(old){if(old.from!==from||old.to!==to||old.service!==service||old.amount!==amount||old.reason!==reason)throw Error('معرف الاسترجاع مستخدم لبيانات مختلفة');return old}
 if(cents(amount)>cents(this.recoverableFunding(from,to,service)))throw Error('المبلغ أكبر من الرصيد المتاح للاسترجاع؛ الرصيد المستخدم أو المحجوز أو الموزع لا يمكن سحبه');
 return atomic(this,()=>{let remaining=cents(amount);const allocations=[];for(const t of this.s.fundingTransfers.filter(t=>t.from===from&&t.to===to&&t.service===service&&t.status!=='معكوس')){const take=Math.min(remaining,Math.max(0,cents(t.amount)-cents(t.recoveredAmount||0)));if(!take)continue;t.recoveredAmount=(cents(t.recoveredAmount||0)+take)/100;allocations.push({transfer:t.id,amount:take/100});remaining-=take;if(!remaining)break}
 const r={id:M.id('RECOVERY'),key,from,to,amount,service,reason,allocations,user:this.user,time:new Date().toISOString()};this.s.fundingRecoveries??=[];this.s.fundingRecoveries.unshift(r);this.serviceEntry(to,service,-amount,'استرجاع رصيد إلى الممول',r.id,from);this.serviceEntry(from,service,amount,'استرداد رصيد موزع',r.id,to);this.log('استرجاع رصيد موزع',r.id,null,r);this.s.notifications.unshift({id:M.id('NT'),target:to,title:'استرجاع رصيد',body:amount+' د.ع • '+reason,time:r.time,user:this.user});return r});
};
const previousReverse=P.reverseFunding;
P.reverseFunding=function(id,reason){const t=this.s.fundingTransfers.find(t=>t.id===id);if(t?.recoveredAmount)throw Error('تم استرجاع جزء من هذا التمويل؛ استخدم استرجاع الرصيد للمبلغ المتبقي');return previousReverse.call(this,id,reason)};
function installRecovery(o){
 const panel=o.components['operations-panel'],data=panel.data;panel.data=function(){return {...data.call(this),recovery:{to:'',amount:'',reason:'',key:M.id('RECOVERY')},recoveryError:''}};
 panel.computed.recoveryFrom=function(){return controller(this.e)};
 panel.computed.recoveryAccounts=function(){return this.accounts.filter(a=>a.id!==this.recoveryFrom&&this.e.recoverableFunding(this.recoveryFrom,a.id,this.service)>0)};
 panel.computed.recoveryLimit=function(){return this.recovery.to?this.e.recoverableFunding(this.recoveryFrom,this.recovery.to,this.service):0};
 panel.computed.recoveryRows=function(){const ids=new Set((this.walletAccounts||this.accounts).map(a=>a.id));return (this.s.fundingRecoveries||[]).filter(r=>(ids.has(r.from)||ids.has(r.to))&&(this.service==='all'||r.service===this.service))};
 panel.methods.resetRecovery=function(){this.recovery={to:'',amount:'',reason:'',key:M.id('RECOVERY')};this.recoveryError=''};
 panel.methods.submitRecovery=function(){this.recoveryError='';try{this.e.recoverFunding(this.recoveryFrom,this.recovery.to,this.recovery.amount,this.service,this.recovery.reason,this.recovery.key);this.resetRecovery();this.vm.notify('تم استرجاع الرصيد إلى محفظة الوكيل وتسجيل الحركة')}catch(error){this.recoveryError=error.message}};
 const reset=panel.methods.reset;panel.methods.reset=function(...args){this.resetRecovery();return reset.apply(this,args)};
 const watch=panel.watch?.service;panel.watch??={};panel.watch.service=function(...args){this.resetRecovery();if(typeof watch==='function')watch.apply(this,args)};
 panel.template=panel.template.replace("{id:'invoice',name:'الفواتير والتحصيل'}","{id:'recovery',name:'استرجاع الرصيد'},{id:'invoice',name:'الفواتير والتحصيل'}");
 const template=`<div v-if="tab==='recovery'" class="card"><form v-if="recoveryFrom && can('wallets.reverse') && service!=='all'" @submit.prevent="submitRecovery"><div class="formgrid"><label>الحساب<select v-model="recovery.to" @change="recovery.amount='';recoveryError=''" required><option value="" disabled>اختر الحساب</option><option v-for="a in recoveryAccounts" :value="a.id">{{name(a.id)}}</option></select></label><label>المبلغ المسترجع · د.ع<input type="number" min="0.01" step="0.01" :max="recoveryLimit" v-model.number="recovery.amount" required></label><label>سبب الاسترجاع<input v-model="recovery.reason" required></label><div><span>المتاح للاسترجاع</span><strong class="ops-number">{{money(recoveryLimit)}} د.ع</strong><button type="button" class="btn" :disabled="!recoveryLimit" @click="recovery.amount=recoveryLimit">كامل المتاح</button></div></div><p v-if="recoveryError" class="notice warn" role="alert">{{recoveryError}}</p><div class="actions"><button class="btn primary" :disabled="!recovery.to || !(recovery.amount>0) || recovery.amount>recoveryLimit || !recovery.reason.trim()">استرجاع إلى محفظتي</button></div></form><p v-else-if="service==='all'" class="empty">اختر محفظة محددة للاسترجاع</p><div class="tablewrap"><table><thead><tr><th>التاريخ</th><th>الحساب المسترجع منه</th><th>الوكيل المستلم</th><th>المبلغ</th><th>السبب</th><th>رقم العملية</th></tr></thead><tbody><tr v-for="r in recoveryRows" :key="r.id"><td>{{vm.formatTime(r.time)}}</td><td>{{name(r.to)}}</td><td>{{name(r.from)}}</td><td>{{money(r.amount)}} د.ع</td><td>{{r.reason}}</td><td>{{r.id}}</td></tr><tr v-if="!recoveryRows.length"><td colspan="6" class="empty">لا توجد عمليات استرجاع</td></tr></tbody></table></div></div>`;
 panel.template=panel.template.replace('<div v-if="tab===\'bulk\'"',template+'<div v-if="tab===\'bulk\'"');
}
root.MasalFundingRules={install(o){install(o);installRecovery(o)}};
})(globalThis);
