(function(root){
'use strict';
function requireTarget(e,id){e.requirePermission('users.reset');if(!['owner','employee','supervisor'].includes(e.actor().role))throw Error('إعادة تعيين كلمة المرور لمدير النظام أو الموظف المخوّل فقط');const u=e.s.users.find(u=>u.id===id);if(!u||u.archivedAt)throw Error('الحساب غير موجود أو مؤرشف');if(e.actor().role!=='owner'){if(u.role==='owner')throw Error('كلمة مرور مدير النظام محمية');if(['employee','supervisor'].includes(u.role)){if(!MasalStaff.scopedUser(e,u))throw Error('المستخدم خارج نطاق صلاحياتك')}else{const account=u.role==='pos'?e.s.pos.find(p=>p.id===u.pos)?.agent:u.agent;if(!account||!e.allowed(account))throw Error('الحساب خارج نطاق صلاحياتك')}}return u}
function validate(){throw Error('استخدم طلب إعادة التعيين؛ صاحب الحساب يختار كلمة مروره بعد التحقق')}
function apply(){throw Error('تغيير كلمة المرور يتطلب تحقق صاحب الحساب')}
const proofs=new WeakMap();
function request(e,id){const u=target(e,id);u.passwordResetRequest={id:crypto.randomUUID(),requestedAt:Date.now(),by:e.user,attempts:0};e.log('طلب إعادة تعيين كلمة المرور',id,null,{by:e.user,demo:true});return u.passwordResetRequest}
function target(e,id){if(['main','sub'].includes(e.actor().role)){e.requirePermission('users.reset');const u=e.s.users.find(u=>u.id===id&&u.active&&!u.archivedAt),own=e.actor().agent,a=u?.role==='pos'?e.s.pos.find(p=>p.id===u.pos)?.agent:u?.agent;if(!u||!['sub','pos'].includes(u.role)||!a||!e.descendants(own).includes(a)||u.id===e.user)throw Error('الحساب خارج نطاق التابعين');return u}const u=requireTarget(e,id);if(!u.active)throw Error('الحساب موقوف');return u}
function pending(s,id){const u=s.users.find(u=>u.id===id&&u.active&&!u.archivedAt);if(!u?.passwordResetRequest)throw Error('لا يوجد طلب إعادة تعيين لهذا الحساب');return u}
function verify(s,id,code){const u=pending(s,id),r=u.passwordResetRequest;if(Date.now()-r.requestedAt>300000)throw Error('انتهت مهلة التحقق؛ اطلب إعادة التعيين مجددًا');if(r.attempts>=5)throw Error('انتهت المحاولات؛ اطلب إعادة التعيين مجددًا');r.attempts++;if(String(code)!=='123456')throw Error('رمز التحقق غير صحيح');const token=crypto.randomUUID();let m=proofs.get(s);if(!m){m=new Map();proofs.set(s,m)}m.set(token,{user:id,request:r.id,expires:Date.now()+300000});return token}
async function complete(s,token,password,confirmation,stillCurrent=()=>true){const proof=proofs.get(s)?.get(token);if(!proof||proof.expires<Date.now())throw Error('تحقق من الرمز مجددًا');const u=pending(s,proof.user);if(u.passwordResetRequest.id!==proof.request)throw Error('تم استبدال طلب التحقق');MasalAuth.passwordPolicy(password);if(password!==confirmation)throw Error('تأكيد كلمة المرور غير مطابق');const before=JSON.stringify(u.credentials),credentials=await MasalStaff.passwordHash(password);if(!stillCurrent()||proofs.get(s)?.get(token)!==proof||proof.expires<Date.now()||!u.active||u.archivedAt||u.passwordResetRequest?.id!==proof.request||JSON.stringify(u.credentials)!==before)throw Error('تغير الطلب أو الحساب؛ أعد التحقق');proofs.get(s).delete(token);u.credentials=credentials;u.mustChangePassword=false;delete u.passwordResetRequest;MasalAuth.revoke(s,u.id);new Masal.Engine(s,u.id).log('تعيين كلمة المرور بواسطة صاحب الحساب',u.id,null,{demo:true,sessionsRevoked:true});return u.id}
const panel={data:()=>({open:false,id:'',code:'',password:'',confirmation:'',token:'',error:'',busy:false}),computed:{vm(){return this.$root},pendingId(){return !this.vm.loginScreen&&this.vm.actor?.passwordResetRequest?.id},name(){return this.vm.s.users.find(u=>u.id===this.id)?.name||''}},watch:{pendingId(v){if(v)this.start(this.vm.currentUser)},'vm.currentUser'(){this.close()},'vm.loginScreen'(){this.close()}},mounted(){if(this.pendingId)this.start(this.vm.currentUser)},methods:{start(id){this.id=id;this.code='';this.password='';this.confirmation='';this.token='';this.error='';this.open=true;this.$nextTick(()=>{if(!this.$refs.dialog.open)this.$refs.dialog.showModal()})},close(){this.open=false;this.token='';this.password='';this.confirmation='';this.$refs.dialog?.close()},begin(){try{const q=this.vm.loginName.trim().toLowerCase(),users=this.vm.s.users.filter(u=>u.active&&!u.archivedAt&&[u.email,u.username,u.name].some(v=>v&&v.toLowerCase()===q));if(users.length!==1)throw Error('أدخل اسم الحساب أو البريد الصحيح أولًا');pending(this.vm.s,users[0].id);this.start(users[0].id)}catch(e){this.vm.loginError=e.message}},async submit(){if(this.busy)return;this.error='';try{if(!this.token){this.token=verify(this.vm.s,this.id,this.code);this.code='';this.vm.persist();return}this.busy=true;const s=this.vm.s,id=this.id,token=this.token;await complete(s,token,this.password,this.confirmation,()=>this.open&&this.vm.s===s&&this.id===id&&this.token===token);this.vm.persist();this.close();this.vm.logoutToLogin();this.vm.loginError='تم تغيير كلمة المرور؛ سجّل الدخول بالكلمة الجديدة'}catch(e){this.error=e.message;this.vm.persist()}finally{this.busy=false}}},template:`<div><button v-if="vm.loginScreen" type="button" class="btn reset-login-link" @click="begin">إعادة تعيين كلمة المرور</button><teleport to="body"><dialog ref="dialog" class="reset-password-dialog" @cancel.prevent="close"><form @submit.prevent="submit"><h2>{{token?'أدخل كلمة مرور جديدة':'التحقق من الحساب'}}</h2><p>{{name}}</p><p class="notice warn">وضع تجربة محلي — الرمز 123456. لم تُرسل رسالة واتساب.</p><template v-if="!token"><label>رمز التحقق<input v-model="code" inputmode="numeric" autocomplete="one-time-code" maxlength="6" pattern="[0-9]{6}" required></label></template><template v-else><label>كلمة المرور الجديدة<input type="password" v-model="password" minlength="10" autocomplete="new-password" required></label><label>تأكيد كلمة المرور<input type="password" v-model="confirmation" minlength="10" autocomplete="new-password" required></label></template><p v-if="error" role="alert">{{error}}</p><div class="formfoot"><button type="button" class="btn" :disabled="busy" @click="close">إلغاء</button><button class="btn primary" :disabled="busy">{{token?'حفظ كلمة المرور':'تحقق'}}</button></div></form></dialog></teleport></div>`};
function install(o){o.components['password-reset-panel']=panel;o.methods.canResetUserPassword=function(id){try{target(this.engine,id);return true}catch{return false}};o.methods.requestPasswordReset=function(id){this.run(()=>{request(this.engine,id);this.persist()},'تم طلب إعادة التعيين؛ صاحب الحساب يتحقق بالرمز التجريبي')};}
root.MasalPasswordAdmin={requireTarget:target,validate,apply,install,request,verify,complete};
})(globalThis);
