(function(root){
function install(o){const data=o.data;o.data=function(){return {...data.call(this),posReturnUser:'',posMore:false}};Object.assign(o.computed,{
 posAppPoint(){return this.s.pos.find(p=>p.id===this.actor.pos)||null},
 posAppTabs(){return [{id:'dashboard',label:'الرئيسية'},{id:'sell',label:'بيع'},{id:'sales',label:'العمليات'},{id:'wallets',label:'الرصيد'}].filter(n=>this.can(n.id+'.view'))},
 posAppMore(){return this.navGroups.flatMap(g=>g.items).filter(n=>!['dashboard','sell','sales','wallets'].includes(n.id))},
 posAppSales(){return this.s.sales.filter(t=>t.pos===this.actor.pos).slice().reverse()},
 posAppBalance(){return this.posAppPoint?this.engine.serviceAvailable(this.actor.pos,'voucher'):0}
 });Object.assign(o.methods,{
 openPOSApp(point){this.run(()=>{this.engine.requirePermission('pos.view',point.agent);if(!this.visiblePOS.some(p=>p.id===point.id))throw Error('نقطة البيع خارج نطاقك');if(!point.active)throw Error('نقطة البيع موقوفة');const user=this.s.users.find(u=>u.active&&u.role==='pos'&&u.pos===point.id);if(!user)throw Error('أنشئ حساب موظف نقطة بيع واربطه بهذه النقطة أولًا من الهوية والمستخدمون');this.posReturnUser=this.currentUser;this.currentUser=user.id;this.switchUser();this.go('dashboard')})},
 leavePOSApp(){const previous=this.posReturnUser;this.posReturnUser='';this.posMore=false;if(previous&&this.s.users.some(u=>u.id===previous&&u.active)){this.currentUser=previous;this.switchUser();this.go('pos')}},
 posNavigate(page){this.posMore=false;this.go(page);this.$nextTick(()=>{const screen=document.querySelector('.pos-application .main');if(screen)screen.scrollTop=0})}
 });o.components??={};o.components['pos-app-home']={computed:{v(){return this.$root}},template:`<section class="pos-home"><div class="pos-wallet-hero"><span>الرصيد المتاح للبطاقات</span><strong>{{v.money(v.posAppBalance)}} <small>د.ع</small></strong><div class="pos-wallet-meta"><span>{{v.posAppPoint?.active?'النقطة مفعلة':'النقطة موقوفة'}}</span><span>{{v.posAppPoint?.serial}}</span></div><button v-if="v.can('sell.view')" class="pos-sell-cta" @click="v.posNavigate('sell')">بيع بطاقة جديدة <span>＋</span></button></div><div class="pos-mini-stats"><div><small>عمليات النقطة</small><strong>{{v.posAppSales.length}}</strong></div><div><small>إجمالي المبيعات</small><strong>{{v.money(v.posAppSales.reduce((n,t)=>n+t.total,0))}} <small>د.ع</small></strong></div></div><div class="pos-shortcuts"><button v-if="v.can('wallets.view')" @click="v.posNavigate('wallets')"><span>↗</span>طلب رصيد</button><button v-if="v.can('exceptions.view')" @click="v.posNavigate('exceptions')"><span>▤</span>متابعة الطباعة</button><button v-if="v.can('support.view')" @click="v.posNavigate('support')"><span>☏</span>الدعم الفني</button></div><div class="card pos-recent"><div class="cardhead"><h2>آخر العمليات</h2><button v-if="v.can('sales.view')" class="btn ghost small" @click="v.posNavigate('sales')">عرض الكل</button></div><p v-if="!v.posAppSales.length" class="empty">لا توجد عمليات بعد. ابدأ ببيع أول بطاقة.</p><article v-for="t in v.posAppSales.slice(0,5)" :key="t.id"><div><b>{{v.nameOf('products',t.product)}}</b><small>{{v.formatTime(t.time)}}</small></div><div><b>{{v.money(t.total)}} د.ع</b><span class="badge" :class="v.statusClass(t.status)">{{v.status(t.status)}}</span></div></article></div><div class="pos-agent-note">الوكيل التابع له: <b>{{v.nameOf('agents',v.actor.agent)}}</b></div></section>`};}
root.MasalPOSApp={install};
})(globalThis);
