(function(root){
'use strict';
const table={computed:{vm(){return this.$root}},template:`<div><div class="toolbar"><input v-model="vm.search" placeholder="بحث باسم الشركة"></div><div class="tablewrap"><table><thead><tr><th>الشعار</th><th>الشركة</th><th>المجهز</th><th>نوع الربط</th><th>الحالة</th><th>الإجراءات</th></tr></thead><tbody><tr v-for="p in vm.filteredRows" :key="p.id"><td><img v-if="p.logo" :src="p.logo" :alt="p.name" class="category-thumb"><span v-else>—</span></td><td>{{p.name}}</td><td>{{p.supplier}}</td><td>{{p.connection}}</td><td><span class="badge" :class="{neutral:!p.active}">{{p.active?'مفعلة':'معطلة'}}</span></td><td><div class="actions"><button class="btn small" @click="vm.previewProvider(p)">معاينة</button><button v-if="vm.can('providers.edit')" class="btn small" @click="vm.openEdit(p)">تعديل</button><button v-if="vm.can('providers.toggle')" class="btn small" @click="vm.toggleEntity(p)">{{p.active?'تعطيل':'تفعيل'}}</button></div></td></tr></tbody></table></div><div v-if="!vm.filteredRows.length" class="empty">لا توجد شركات مطابقة</div></div>`};
const editor={computed:{vm(){return this.$root}},template:`<div v-if="vm.can('providers.images')" class="formgrid"><label>شعار الشركة (اختياري)<image-attachment v-model="vm.editForm.logo" @busy="vm.providerLogoBusy=$event"></image-attachment></label></div>`};
const preview={props:['provider'],computed:{vm(){return this.$root}},template:`<div><dl class="account-fields"><div><dt>الشركة</dt><dd>{{provider.name}}</dd></div><div><dt>المجهز</dt><dd>{{provider.supplier}}</dd></div><div><dt>نوع الربط</dt><dd>{{provider.connection}}</dd></div><div><dt>الحالة</dt><dd>{{provider.active?'مفعلة':'معطلة'}}</dd></div><div><dt>الشعار</dt><dd><img v-if="provider.logo" :src="provider.logo" alt="الشعار" class="category-preview-image"><span v-else>—</span></dd></div></dl><div class="formfoot"><button class="btn" @click="vm.closeModal()">إغلاق</button><button v-if="vm.can('providers.edit')" class="btn primary" @click="vm.openEdit(provider)">تعديل</button></div></div>`};
function install(o){
const data=o.data;o.data=function(){return {...data.call(this),providerLogoBusy:false}};
editor.components={'image-attachment':o.components['image-attachment']};
Object.assign(o.components,{'provider-table':table,'provider-editor':editor,'provider-preview':preview});
const open=o.methods.openEdit;o.methods.openEdit=function(row){open.call(this,row);if(this.page==='providers'&&this.modal?.kind==='edit'){this.providerLogoBusy=false;this.editForm.logo??='';this.modal.title=row?'تعديل الشركة':'إضافة شركة'}};
const save=o.methods.saveEntity;o.methods.saveEntity=function(){if(this.page==='providers'){if(this.providerLogoBusy)return;try{const old=this.s.providers.find(p=>p.id===this.editForm.id);if(['logo'].some(k=>(this.editForm[k]||'')!==(old?.[k]||'')))this.engine.requirePermission('providers.images')}catch(e){this.notify(e.message,true);return}}return save.call(this)};
o.methods.previewProvider=function(p){this.run(()=>{this.engine.requirePermission('providers.view');this.modal={kind:'providerPreview',title:'معاينة الشركة',provider:Masal.clone(p)}})};
}
root.MasalProvidersUI={install};
})(globalThis);
