(function(root){
'use strict';
const definitions=[{id:'sales',title:'المبيعات والأرباح',icon:'reports',prefixes:['sales','prices'],note:'المبيعات والطباعة والأسعار'},{id:'wallets',title:'المحافظ والتمويل',icon:'wallets',prefixes:['wallets'],note:'الأرصدة والتمويل والتحصيل'},{id:'inventory',title:'البطاقات والمخزون',icon:'inventory',prefixes:['inventory','claims'],note:'الدفعات والبطاقات والمطالبات'},{id:'network',title:'الوكلاء ونقاط البيع',icon:'agents',prefixes:['network'],note:'شبكة التوزيع وحالة الحسابات'},{id:'admin',title:'المتابعة الإدارية',icon:'audit',prefixes:['users','audit','support','operations'],note:'التغييرات والدعم والإشعارات'}];
const details={computed:{vm(){return this.$root}},template:`<div class="report-detail-dialog"><p class="help">{{vm.tr(vm.reportActive?.note||'')}}</p><div class="report-table-tools"><input v-model="vm.reportSearch" :placeholder="vm.tr('بحث داخل التقرير')" :aria-label="vm.tr('بحث داخل التقرير')"><details class="column-picker"><summary class="btn">{{vm.tr('الأعمدة')}}</summary><div><label v-for="c in vm.reportActive?.columns||[]" class="inline-check"><input type="checkbox" :checked="!vm.reportHidden.includes(c.key)" @change="$event.target.checked?vm.reportHidden=vm.reportHidden.filter(k=>k!==c.key):vm.reportHidden.push(c.key)">{{vm.tr(c.label)}}</label></div></details><button v-if="vm.can('reports.export')" class="btn" @click="vm.downloadReportDocument()">Excel</button><button v-if="vm.can('reports.print')" class="btn" @click="vm.printReport()">{{vm.tr('طباعة / حفظ PDF')}}</button></div><div class="tablewrap"><table><thead><tr><th v-for="c in vm.reportColumns"><button class="table-sort" @click="vm.sortReport(c.key)">{{vm.tr(c.label)}} {{vm.reportSort.key===c.key?(vm.reportSort.direction===1?'↑':'↓'):''}}</button></th><th v-if="['sales','audit'].includes(vm.reportActive?.id)">الإجراءات</th></tr></thead><tbody><tr v-for="(row,i) in vm.reportFilteredRows" :key="i"><td v-for="c in vm.reportColumns">{{vm.reportCell(row[c.key],c)}}</td><td v-if="['sales','audit'].includes(vm.reportActive?.id)"><div class="actions"><template v-if="vm.reportActive.id==='sales'&&vm.reportSale(row)"><button v-if="vm.canViewSaleCards(vm.reportSale(row))" class="btn small" @click="vm.reportRecordAction(row,'receipt')">الوصل</button><button v-if="vm.canViewSaleCards(vm.reportSale(row))&&vm.can('sell.reprint')&&['Printed','Print Failed','Reprinted'].includes(vm.reportSale(row).status)" class="btn small" @click="vm.reportRecordAction(row,'reprint')">إعادة طباعة</button><button v-if="vm.canViewSaleCards(vm.reportSale(row))&&vm.can('sell.receipt')&&['Print Requested','Reprint Requested'].includes(vm.reportSale(row).status)" class="btn small" @click="vm.reportRecordAction(row,'receipt')">متابعة الطباعة</button></template><button v-if="vm.can('audit.details')" class="btn small" @click="vm.reportRecordAction(row,'inspect')">السجل</button></div></td></tr><tr v-if="!vm.reportFilteredRows.length"><td :colspan="Math.max(1,vm.reportColumns.length)" class="empty">{{vm.tr('لا توجد سجلات ضمن الفلاتر الحالية')}}</td></tr></tbody></table></div><div class="formfoot"><button v-if="vm.reportDestination" class="btn primary" @click="vm.goToReportDestination()">{{vm.tr(vm.reportDestination.label)}}</button><button class="btn" @click="vm.closeModal()">{{vm.tr('رجوع إلى التقارير')}}</button></div></div>`};
root.MasalReportGroups={install(o){const nav=o.computed.navGroups;o.computed.navGroups=function(){return nav.call(this).map(g=>({...g,items:g.items.filter(n=>!['sales','audit','monitoring'].includes(n.id)).map(n=>({...n,label:n.id==='reports'?'مركز التقارير والعمليات':n.label}))})).filter(g=>g.items.length)};
const go=o.methods.go;o.methods.go=function(page,...args){if(['sales','audit','monitoring'].includes(page)){const group=page==='audit'?'admin':page==='sales'?'sales':'';const result=go.call(this,'reports',...args);if(this.page==='reports'){this.reportOpenGroup=group;if(page==='sales'&&this.statusFilter)this.reportStatus=this.statusFilter;}return result}return go.call(this,page,...args)};
const data=o.data;o.data=function(){return {...data.call(this),reportOpenGroup:'',reportDetailReturn:null}};o.components['report-detail-dialog']=details;
o.computed.reportGroups=function(){return definitions.map(g=>({...g,sections:this.reportBundle.sections.filter(s=>g.prefixes.includes(s.id.split('-')[0]))})).filter(g=>g.sections.length)};
o.computed.reportTypeScope=function(){const group=definitions.find(g=>g.id===this.reportOpenGroup);const sections=this.reportBundle.sections;return group?sections.filter(s=>group.prefixes.includes(s.id.split('-')[0])):sections};
o.computed.selectedReportGroup=function(){const group=this.reportGroups.find(g=>g.id===this.reportOpenGroup);if(!group)return;const cards=group.sections.map(s=>({id:s.id,title:s.id==='sales'?'سجل العمليات':s.id==='audit'?'سجل التغييرات':s.title,count:s.rows.length,filter:''}));const add=(id,title,filter)=>{const section=group.sections.find(s=>s.id===id);if(section)cards.push({id,title,filter,count:section.rows.filter(r=>this.reportDetailMatches(r,filter)).length})};if(group.id==='network'){add('network','الوكلاء الرئيسيون','main');add('network','الفروع','branch');add('network','الفروع الفرعية','nested');add('network-pos','نقاط البيع النشطة','active');add('network-pos','نقاط البيع المعطّلة','inactive')}if(group.id==='inventory'){add('inventory-cards','البطاقات المتاحة','available');add('inventory-cards','البطاقات المباعة','issued');add('inventory-cards','البطاقات المحجورة والمصدّرة','held')}return {...group,cards}};
o.methods.reportDetailMatches=function(r,key){if(!key)return true;if(key==='main')return r.type==='رئيسي';if(key==='branch'||key==='nested'){const a=this.s.agents.find(a=>a.id===r.id),nested=this.s.agents.some(p=>p.id===a?.parent&&p.type==='فرعي');return a?.type==='فرعي'&&(key==='nested'?nested:!nested)}if(key==='active')return r.active==='مفعل';if(key==='inactive')return r.active==='موقوف';return ({available:['Available'],issued:['Issued'],held:['Quarantined','Exported','Awaiting Replacement']}[key]||[]).includes(r.status)};
const active=o.computed.reportActive;o.computed.reportActive=function(){const section=active.call(this);if(!section||this.modal?.kind!=='reportDetails'||!this.modal.filter)return section;return {...section,title:this.modal.title,rows:section.rows.filter(r=>this.reportDetailMatches(r,this.modal.filter))}};
o.methods.toggleReportGroup=function(id){const closing=this.reportOpenGroup===id;this.reportOpenGroup=closing?'':id;if(!closing){this.reportKind='all';this.reportSection='sales';}};
o.methods.openReportDetails=function(id,filter='',title=''){const section=this.reportSections.find(s=>s.id===id);if(!section)return;this.selectReport(id);this.modal={kind:'reportDetails',title:title||section.title,filter};};
o.computed.reportDestination=function(){
 if(this.modal?.kind!=='reportDetails')return null;
 const targets={inventory:['inventory','المخزون'],'inventory-cards':['inventory','المخزون'],'inventory-purchases':['import','الطلبيات'],'inventory-invoices':['wallets','المحافظ والتحويلات'],'inventory-products':['products','الفئات'],'inventory-providers':['providers','الشركات'],wallets:['wallets','المحافظ والتحويلات'],'wallets-ledger':['wallets','المحافظ والتحويلات'],'wallets-legacy':['wallets','المحافظ والتحويلات'],network:['agents','الوكلاء'],'network-pos':['pos','نقاط البيع'],prices:['prices','الأسعار'],'prices-approvals':['prices','الأسعار'],claims:['claims','البطاقات التالفة'],'claims-exports':['exports','تصدير البطاقات'],support:['support','الدعم الفني'],'support-replies':['support','الدعم الفني'],users:['users','المستخدمين'],operations:['security','الحماية والأمان'],'operations-notifications':['notifications','الإشعارات']};
 const target=targets[this.reportActive?.id];return target&&this.can(target[0]+'.view')?{page:target[0],label:'الانتقال إلى '+target[1]}:null;
};
o.methods.goToReportDestination=async function(){const target=this.reportDestination;if(!target||!this.can(target.page+'.view'))return;const section=this.reportActive.id,filter=this.modal.filter,context={agent:this.reportAgent,pos:this.reportPOS,product:this.reportProduct,provider:this.reportProvider,city:this.reportCity,from:this.reportFrom,to:this.reportTo};this.reportDetailReturn=null;this.closeModal();this.go(target.page);if(this.page!==target.page)return;this.search='';this.statusFilter='';await this.$nextTick();
 if(target.page==='wallets'){this.walletFilters={...this.emptyWalletFilters(),network:context.agent,account:context.pos,city:context.city,from:context.from,to:context.to};const panel=this.$refs.operations;if(panel){panel.tab=section==='inventory-invoices'?'invoice':'balances';panel.account=context.pos||'';panel.service='voucher'}}
 if(target.page==='inventory'){this.inventoryAgent=this.inventoryAgents.some(a=>a.id===context.agent)?context.agent:'';if(context.product)this.search=this.nameOf('products',context.product)}
 if(target.page==='agents'){this.networkKind=({main:'main',branch:'sub',nested:'subsub'})[filter]||'all';this.networkSearch='';if(context.agent){const name=this.nameOf('agents',context.agent);this.search=name;this.networkSearch=name}}
 if(target.page==='pos'&&context.pos)this.search=this.nameOf('pos',context.pos);
 if(target.page==='products'&&context.product)this.search=this.nameOf('products',context.product);
 if(target.page==='providers'&&context.provider)this.search=this.nameOf('providers',context.provider);
 if(target.page==='prices'&&this.scopeFilterAgents.some(a=>a.id===context.agent&&a.type==='رئيسي'))this.priceAgent=context.agent;
};
o.methods.reportSale=function(row){return this.visibleSales.find(t=>t.id===row.id)};
o.methods.reportRecordAction=function(row,action){const original=this.modal,record=this.reportActive?.id==='sales'?this.reportSale(row):this.auditRows.find(r=>r.id===row.id);if(!record)return;this.reportDetailReturn={...original};if(action==='receipt')this.viewReceipt(record);else if(action==='reprint')this.openReprint(record);else this.inspect(record);if(this.modal===original)this.reportDetailReturn=null};
const close=o.methods.closeModal;o.methods.closeModal=function(...args){const back=this.reportDetailReturn;this.reportDetailReturn=null;const result=close.apply(this,args);if(back&&this.page==='reports')this.modal=back;return result};
const exports=o.methods.reportExportSections;o.methods.reportExportSections=function(all){if(this.modal?.kind==='reportDetails')return this.reportActive?[{...this.reportActive,columns:this.reportColumns,rows:this.reportFilteredRows}]:[];return exports.call(this,all)};
const change=o.methods.switchUser;o.methods.switchUser=function(...args){this.reportOpenGroup='';this.reportDetailReturn=null;return change.apply(this,args)};
}};
})(window);
