from pathlib import Path
p=Path('index.html');h=p.read_text(encoding='utf-8-sig')
h=h.replace('<title>ماسال', '''<script>try{document.documentElement.dataset.theme=localStorage.getItem('masal-appearance')||'light'}catch(e){document.documentElement.dataset.theme='light'}</script><title>ماسال''',1)
h=h.replace('<div class="brandmark">م</div>', '<div class="brandmark"><svg width="25" height="25" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round"><rect x="2" y="5" width="20" height="14" rx="3"/><path d="M2 10h20M7 15h1m3 0h2"/></svg></div>',1)
h=h.replace('<div class="toptools">','''<div class="toptools"><button class="iconbtn theme-toggle" @click="toggleTheme" :aria-label="theme==='light'?'تفعيل الوضع الليلي':'تفعيل الوضع النهاري'" :title="theme==='light'?'الوضع الليلي':'الوضع النهاري'" :aria-pressed="theme==='dark'"><svg v-if="theme==='light'" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M20.5 14A8.5 8.5 0 0 1 10 3.5 8.5 8.5 0 1 0 20.5 14Z"/></svg><svg v-else viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/></svg></button>''',1)
h=h.replace('<div class="breadcrumb">مساحة العمل <span> / </span><b>{{title}}</b></div>','''<div class="breadcrumb"><strong>ماسال كاردز</strong><span class="badge">Cards & Operations</span><small>Telecom Operations & Merchant Settlement System</small></div>''')
h=h.replace('<h1>{{title}}</h1>','<h1>{{page===\'dashboard\'?\'نظرة عامة على المبيعات\':title}} <small v-if="page===\'dashboard\'">Sales Overview</small></h1>',1)
start=h.index('<template v-if="page===\'dashboard\'">')
end=h.index('<div class="dashboardgrid"><div class="card"><div class="cardhead"><div><h2>آخر العمليات',start)
dashboard='''<template v-if="page==='dashboard'">
<section class="reference-metrics" data-purpose="top-metric-cards-row">
<div class="metric-stack">
<div class="card sales-hero"><div class="cardhead"><span><i class="dot"></i>إجمالي مبيعات التجزئة والجملة • Total Sales</span><button class="more" @click="go('sales')" aria-label="عرض المبيعات">•••</button></div><div class="sales-main"><div><div class="metricvalue">{{money(totalSales)}} <small>د.ع</small></div><span class="metricsub">{{visibleSales.length}} عملية بيع مسجلة</span></div><span class="sales-chip">↗ الربح الإجمالي <b>{{money(reportMetrics[2].value)}} د.ع</b></span></div><div class="sales-breakdown"><span v-for="(p,i) in s.providers.slice(0,3)"><i :style="{background:['#fbbf24','#a78bfa','#38bdf8'][i]}"></i>{{p.name}}: {{visibleSales.filter(t=>s.products.find(c=>c.id===t.product)?.provider===p.id).length}}</span></div></div>
<div class="card purchase-card"><div class="cardhead"><span>إجمالي الشراء والتوريد • Total Purchase</span><button class="more" @click="go('inventory')" aria-label="عرض المخزون">•••</button></div><div class="metricvalue">{{money(visibleBatches.reduce((n,b)=>n+b.cost*b.quantity+(+b.expenses||0),0))}} <small>د.ع</small></div><span class="caption">تكلفة استلام الدفعات ومصاريف التوريد</span><div class="card-bottom"><span>الرصيد المتبقي بالمستودع الرقمي:</span><b>{{money(availableCards.length)}} كود متاح</b></div></div>
</div>
<div class="card growth-card" data-purpose="growth-card"><div><div class="cardhead"><h2>الحسابات والوكلاء <small>User Growth</small></h2><button class="more" @click="go('agents')" aria-label="عرض الوكلاء">•••</button></div><div class="tabs reference-tabs" role="group" aria-label="عرض الحسابات"><button :class="{active:accountTab==='all'}" @click="accountTab='all'">الكل</button><button :class="{active:accountTab==='main'}" @click="accountTab='main'">رئيسي</button><button :class="{active:accountTab==='sub'}" @click="accountTab='sub'">فرعي</button><button :class="{active:accountTab==='pos'}" @click="accountTab='pos'">نقاط البيع</button></div><div class="growth-value"><span class="metricvalue">{{accountTab==='pos'?visiblePOS.length:accountTab==='main'?visibleAgents.filter(a=>a.type==='رئيسي').length:accountTab==='sub'?visibleAgents.filter(a=>a.type==='فرعي').length:visibleAgents.length+visiblePOS.length}}</span><span class="badge">{{visibleAgents.filter(a=>a.active).length+visiblePOS.filter(p=>p.active).length}} حساب فعال</span></div><p class="caption">حسابات الوكلاء والموزعين ونقاط البيع في نطاقك</p><div class="wide-progress"><i :style="{width:((visibleAgents.filter(a=>a.active).length+visiblePOS.filter(p=>p.active).length)/Math.max(1,visibleAgents.length+visiblePOS.length)*100)+'%'}"></i></div><div class="progress-labels"><span>الحسابات المفعلة / إجمالي الشبكة</span><b>{{Math.round((visibleAgents.filter(a=>a.active).length+visiblePOS.filter(p=>p.active).length)/Math.max(1,visibleAgents.length+visiblePOS.length)*100)}}%</b></div></div><div class="card-bottom"><span><i class="dot"></i>أرصدة المحافظ المستقلة</span><b class="wallet-pill">{{money(totalWallets)}} د.ع</b></div></div>
<div class="card volume-card" data-purpose="volume-card"><div><div class="cardhead"><h2>نشاط نقاط البيع <small>POS Volume</small></h2><button class="more" @click="go('pos')" aria-label="عرض نقاط البيع">•••</button></div><div class="gauge"><svg viewBox="0 0 200 115" aria-label="نسبة نقاط البيع المتصلة"><defs><linearGradient id="masalGauge" x1="0%" x2="100%"><stop offset="0%" stop-color="#00C7B1"/><stop offset="60%" stop-color="#0284C7"/><stop offset="100%" stop-color="#38BDF8"/></linearGradient></defs><path d="M20 100 A80 80 0 0 1 180 100" fill="none" class="gauge-track" stroke-width="16" stroke-linecap="round"/><path d="M20 100 A80 80 0 0 1 180 100" fill="none" stroke="url(#masalGauge)" stroke-width="16" stroke-linecap="round" :stroke-dasharray="(visiblePOS.filter(p=>p.online&&p.active).length/Math.max(1,visiblePOS.length)*251.3)+' 260'" class="gauge-fill"/></svg><div class="gauge-label"><strong>{{visiblePOS.filter(p=>p.online&&p.active).length}}</strong><span>نقطة متصلة / Online POS</span></div></div><div class="pos-summary"><span>نقاط البيع النشطة (POS):</span><b>{{visiblePOS.filter(p=>p.active).length}} <small>/ {{visiblePOS.length}} جهاز</small></b></div></div><div class="card-bottom"><span>عمليات تحتاج متابعة</span><button class="badge warn" @click="go('exceptions')">{{exceptions.length}} عملية</button></div></div>
</section>
<section class="reference-bottom" data-purpose="bottom-charts-and-region-row"><div class="card statistics-card"><div class="cardhead"><div><h2>إحصائيات الإرسال والمبيعات <small>Statistics</small></h2><div class="caption">توزيع وتيرة المبيعات والأداء اليومي لنقاط السحب</div></div><span class="wallet-pill">أسبوعي (Weekly)</span></div><div class="statistics-body"><div class="chart-stat"><div class="metricvalue">{{money(weekTotal)}}</div><p class="caption">دينار عراقي • إجمالي المبيعات خلال آخر سبعة أيام</p><span class="badge">{{visibleSales.filter(t=>Date.now()-Date.parse(t.time)<7*86400000).length}} عملية</span></div><div class="chart-area"><div class="chart"><div v-for="b in chart" class="barcol" :class="{today:b.today}"><small>{{money(b.value)}}</small><div class="bar" :style="{height:(b.value?Math.max(8,b.value/chartMax*170):3)+'px'}" :title="b.label+': '+money(b.value)+' د.ع'"></div></div></div><div class="chartlabels"><span v-for="b in chart">{{b.label}}</span></div></div></div><div class="card-bottom"><span><i class="dot"></i>بيانات المبيعات المسجلة في النظام</span><button class="btn ghost small" @click="go('reports')">تحميل التقرير التفصيلي الكامل ←</button></div></div>
<div class="card region-card"><div class="cardhead"><div><h2><span class="region-flag">🇮🇶</span> توزيع الوكلاء والمحافظات <small>By Province</small></h2><div class="caption">المخزون ونقاط البيع التابعة للوكلاء الرئيسيين</div></div></div><div class="region-list"><div v-for="(a,i) in visibleAgents.filter(a=>a.type==='رئيسي')" class="region-row"><div class="rowidentity"><div class="square" :style="{background:['linear-gradient(135deg,#2563eb,#4338ca)','linear-gradient(135deg,#0d9488,#0e7490)','linear-gradient(135deg,#9333ea,#6d28d9)'][i%3],color:'#fff'}">{{a.name.slice(0,1)}}</div><div><b>{{a.name}}</b><small>{{s.pos.filter(p=>engine.descendants(a.id).includes(p.agent)).length}} نقاط بيع • {{availableCards.filter(c=>c.agent===a.id).length}} بطاقة متاحة</small><div class="progress"><i :style="{background:a.color,width:Math.min(100,availableCards.filter(c=>c.agent===a.id).length/Math.max(1,availableCards.length)*100)+'%'}"></i></div></div></div><span class="province-pill">{{a.city}}</span></div></div><div class="card-bottom"><span><i class="dot"></i>نطاق شبكة التوزيع</span><button class="btn ghost small" @click="go('map')">عرض الخريطة التفاعلية ←</button></div></div></section>
'''
h=h[:start]+dashboard+h[end:]
p.write_text(h,encoding='utf-8')
p=Path('app.js');s=p.read_text(encoding='utf-8-sig');s=s.replace("page:'dashboard',navSearch:","page:'dashboard',theme:document.documentElement.dataset.theme||'light',accountTab:'all',navSearch:",1)
s=s.replace('methods:{money(n)',"methods:{toggleTheme(){this.theme=this.theme==='light'?'dark':'light';document.documentElement.dataset.theme=this.theme;try{localStorage.setItem('masal-appearance',this.theme)}catch(e){this.notify('تعذر حفظ تفضيل المظهر',true)}},money(n)",1)
p.write_text(s,encoding='utf-8')
