const assert=require('node:assert/strict');const {Engine,seed}=require('./test-credit-fixture.cjs');
let count=0;function test(name,fn){fn();count++;console.log('PASS '+name)}
test('Daily business limits use Baghdad time',()=>{const {businessDay}=require('./test-credit-fixture.cjs');assert.equal(businessDay('2026-09-16T22:30:00Z'),'2026-09-17');assert.equal(businessDay('2026-09-16T19:00:00Z'),'2026-09-16')});
test('Inventory intake preserves cash, adds voucher credit; duplicate PIN rejected',()=>{const e=new Engine(),balance=e.balance('A1'),meta={agent:'A1',product:'C1',cost:4000,expenses:100,expiry:'2028-12-31'};const rows=[{pin:'UNIQUE-DEMO-1',serial:'NEW-1',expiry:'2028-12-31'},{pin:'UNIQUE-DEMO-1',serial:'NEW-2',expiry:'2028-12-31'},{pin:'',serial:'NEW-3',expiry:'2028-12-31'}];const b=e.importBatch(meta,rows);assert.equal(b.quantity,1);assert.equal(e.balance('A1'),balance);assert.equal(e.s.cards.find(c=>c.batch===b.id).cost,4100)});
test('Transfers are balanced and scoped to children',()=>{const e=new Engine();e.user='U3';const total=e.s.serviceLedger.reduce((n,l)=>n+l.amount,0);e.transfer('A1','A3',10000);assert.equal(e.s.serviceLedger.reduce((n,l)=>n+l.amount,0),total);assert.throws(()=>e.transfer('A1','A2',1));assert.throws(()=>e.transfer('A1','A3',1e10));assert.throws(()=>e.transfer('A1','A3',-10))});
test('Sub-agent uses main inventory; idempotency avoids second charge',()=>{const e=new Engine(seed(),'U4'),balance=e.serviceBalance('POS1');const t=e.sell('POS1','C1',2,'same-key');assert.equal(e.serviceBalance('POS1'),balance-t.credit);assert.ok(t.cards.every(id=>e.s.cards.find(c=>c.id===id).agent==='A1'));assert.equal(e.sell('POS1','C1',2,'same-key').id,t.id);assert.equal(e.s.sales.length,1);assert.throws(()=>e.sell('POS3','C1',1,'other-key'))});
test('Failed printing cannot release exposed PIN; reprint keeps cards and wallet',()=>{const e=new Engine();const t=e.sell('POS1','C1',1,'print');e.printResult(t.id,false);assert.equal(e.s.cards.find(c=>c.id===t.cards[0]).status,'Print Failed');const balance=e.serviceBalance('POS1'),ids=[...t.cards];e.reprint(t.id,'paper replaced');e.printResult(t.id,true);assert.deepEqual(t.cards,ids);assert.equal(e.serviceBalance('POS1'),balance);assert.equal(t.status,'Reprinted');assert.throws(()=>e.printResult(t.id,true));assert.throws(()=>e.batchAction(e.s.cards.find(c=>c.id===t.cards[0]).batch,'cancel'))});
test('Zero price, missing price and insufficient balance block sale',()=>{for(const bad of [0,null]){const e=new Engine();e.s.prices.find(p=>p.agent==='A3'&&p.product==='C1').price=bad;assert.throws(()=>e.sell('POS1','C1',1,'bad'))}const e=new Engine();e.s.serviceLedger=e.s.serviceLedger.filter(l=>l.account!=='POS1');assert.throws(()=>e.sell('POS1','C1',1,'bad'))});
test('Non-owner price changes require another approver and preserve rollback',()=>{const e=new Engine();e.user='U2';const old=e.s.prices.find(p=>p.agent==='A1'&&p.product==='C1').price;const r=e.proposePrices([{agent:'A1',product:'C1',price:4900}]);assert.throws(()=>e.approvePrices(r.id));e.user='U1';e.approvePrices(r.id);assert.equal(e.s.prices.find(p=>p.agent==='A1'&&p.product==='C1').price,4900);e.reversePrices(r.id);assert.equal(e.s.prices.find(p=>p.agent==='A1'&&p.product==='C1').price,old);assert.throws(()=>e.proposePrices([{agent:'A1',product:'C1',price:0}]))});
test('FEFO then FIFO chooses earliest expiration',()=>{const e=new Engine();e.s.cards.find(c=>c.id==='CARD-A1-C1-10').expiry='2027-01-01';const t=e.sell('POS1','C1',1,'fefo');assert.equal(t.cards[0],'CARD-A1-C1-10')});
test('Limits, disabled devices and disabled providers prevent sales',()=>{const e=new Engine();assert.throws(()=>e.sell('POS1','C1',11,'limit'));e.s.settings.sales=false;assert.throws(()=>e.sell('POS1','C1',1,'stop'));e.s.settings.sales=true;e.s.providers[0].active=false;assert.throws(()=>e.sell('POS1','C1',1,'provider'))});
test('Claim quarantine preserves cash; exported PIN never reactivated',()=>{const e=new Engine(),before=e.balance('A1');const c=e.claim('B-A1-C1','defect');assert.equal(e.balance('A1'),before);assert.ok(e.s.cards.filter(x=>x.batch===c.batch).every(x=>x.status==='Quarantined'));e.s.cards.find(x=>x.batch===c.batch).status='Exported';assert.throws(()=>e.settle(c.id,'إعادة تفعيل'))});
test('Hierarchy isolates supervisor, sub-agent and POS',()=>{const e=new Engine(seed(),'U2');assert.equal(e.allowed('A2'),false);assert.equal(e.allowed('A3'),true);e.user='U4';assert.equal(e.allowed('A1'),false);assert.equal(e.allowed('A3'),true);e.user='U5';assert.throws(()=>e.sell('POS2','C1',1,'wrongPOS'))});
console.log(`${count} domain tests passed`);
