(function(root){
'use strict';
const empty=()=>({city:'',kind:'',network:'',account:'',active:'',query:'',reference:'',from:'',to:''});
function kind(vm,a){if(vm.s.pos.some(p=>p.id===a.id))return 'pos';if(a.type==='رئيسي')return 'main';return vm.s.agents.some(p=>p.id===a.parent&&p.type==='فرعي')?'subsub':'sub'}
const labels={main:'وكيل رئيسي',sub:'وكيل فرعي',subsub:'فرعي تابع لفرعي',pos:'نقطة بيع'};
function accounts(vm,rows,f,ignoreAccount=false){const network=f.network?new Set(vm.engine.descendants(f.network)):null,q=f.query.trim().toLocaleLowerCase();return rows.filter(a=>(!f.city||a.city===f.city)&&(!f.kind||kind(vm,a)===f.kind)&&(!network||network.has(vm.s.pos.some(p=>p.id===a.id)?a.agent:a.id))&&(ignoreAccount||!f.account||a.id===f.account)&&(!f.active||!!a.active===(f.active==='active'))&&(!q||[a.name,a.phone,a.city,a.owner].some(v=>String(v||'').toLocaleLowerCase().includes(q))))}
function record(vm,row,f){const q=f.reference.trim().toLocaleLowerCase();if(q&&![row.id,row.group,row.reference,row.batch,row.purpose,row.kind].some(v=>String(v||'').toLocaleLowerCase().includes(q)))return false;if(!f.from&&!f.to)return true;const t=row.time;if(!t||Number.isNaN(Date.parse(t)))return false;const day=Masal.businessDay(t);return (!f.from||day>=f.from)&&(!f.to||day<=f.to)}
const dialog={computed:{vm(){return this.$root},draft(){return this.vm.modal.draft},cities(){return this.vm.scopeFilterCities},networks(){return this.vm.scopeFilterAgents},kinds(){return this.vm.scopeFilterKinds},choices(){const rows=this.vm.actor.role==='owner'?[...this.vm.s.agents,...this.vm.s.pos]:this.vm.accounts;return accounts(this.vm,rows,this.draft,true)}},methods:{changed(field){if(['city','kind'].includes(field))this.draft.network='';if(!this.choices.some(a=>a.id===this.draft.account))this.draft.account=''}},template:`<form @submit.prevent="vm.applyWalletFilters"><div class="formgrid"><label>المحافظة<select aria-label="المحافظة" v-model="draft.city" @change="changed('city')"><option value="">{{vm.actor.role==='owner'?'الكل':vm.actor.role==='pos'?'نقطتي فقط':'الكل ضمن نطاقي'}}</option><option v-for="c in cities" :value="c">{{c}}</option></select></label><label>نوع الحساب<select aria-label="نوع الحساب" v-model="draft.kind" @change="changed('kind')"><option value="">{{vm.actor.role==='pos'?'نقطتي فقط':'الكل ضمن نطاقي'}}</option><option v-for="k in kinds" :value="k.id">{{k.label}}</option></select></label><label v-if="networks.length">شبكة الوكيل<select aria-label="شبكة الوكيل" v-model="draft.network" @change="changed"><option value="">{{vm.actor.role==='pos'?'نقطتي فقط':'الكل ضمن نطاقي'}}</option><option v-for="a in networks" :value="a.id">{{a.name}}</option></select></label><label>حالة الحساب<select aria-label="حالة الحساب" v-model="draft.active" @change="changed"><option value="">{{vm.actor.role==='pos'?'نقطتي فقط':'الكل ضمن نطاقي'}}</option><option value="active">مفعّل</option><option value="inactive">معطّل</option></select></label><label>بحث بالاسم أو الهاتف<input v-model="draft.query" @input="changed" type="search"></label><label>الحساب<select aria-label="الحساب" v-model="draft.account"><option value="">{{vm.actor.role==='pos'?'نقطتي فقط':'الحسابات المطابقة ضمن نطاقي'}}</option><option v-for="a in choices" :value="a.id">{{a.name}} · {{vm.walletAccountType(a)}}</option></select></label><label class="full">رقم الحركة أو المرجع<input v-model="draft.reference" type="search"></label><label>من تاريخ<input type="date" v-model="draft.from" :max="draft.to||undefined"></label><label>إلى تاريخ<input type="date" v-model="draft.to" :min="draft.from||undefined"></label></div><p class="caption">التاريخ والمرجع للسجلات؛ الأرصدة المعروضة حالية.</p><p v-if="vm.modal.error" class="notice warn" role="alert">{{vm.modal.error}}</p><div class="formfoot"><button type="button" class="btn" @click="vm.modal.draft=vm.emptyWalletFilters();vm.modal.error=''">مسح الاختيارات</button><button type="button" class="btn" @click="vm.closeModal()">إلغاء</button><button type="submit" class="btn primary">تطبيق</button></div></form>`};

const accountTable={
 props:['rows','service'],emits:['movements'],data(){return {query:'',type:'',size:10,page:1}},
 computed:{vm(){return this.$root},filtered(){const q=this.query.trim().toLocaleLowerCase();return this.rows.filter(a=>(!this.type||kind(this.vm,a)===this.type)&&(!q||[a.name,a.phone,a.id].some(x=>String(x||'').toLocaleLowerCase().includes(q))))},pages(){return Math.max(1,Math.ceil(this.filtered.length/this.size))},shown(){return this.filtered.slice((this.page-1)*this.size,this.page*this.size)}},
 watch:{query(){this.page=1},type(){this.page=1},size(){this.page=1},rows(){this.page=1},'vm.currentUser'(){this.query='';this.type='';this.page=1}},
 methods:{parent(a){const id=this.vm.s.pos.some(p=>p.id===a.id)?a.agent:a.parent;return this.vm.accounts.find(x=>x.id===id)?.name||'—'},details(a){this.vm.modal={kind:'walletAccountDetail',title:a.name,accountId:a.id,service:this.service}}},
 template:`<section class="card wallet-accounts-table" data-no-pagination><div class="cardhead"><h3>{{vm.tr('الحسابات والأرصدة')}}</h3><button class="btn" @click="vm.openWalletFilters()">{{vm.tr('فلترة وبحث')}}</button></div><div class="wallet-account-tools"><input type="search" v-model="query" aria-label="بحث الحسابات" :placeholder="vm.tr('بحث باسم الحساب أو الهاتف')"><select v-model="type" aria-label="نوع الحساب في الجدول"><option value="">{{vm.tr('كل الأنواع ضمن نطاقي')}}</option><option v-for="k in vm.scopeFilterKinds" :value="k.id">{{vm.tr(k.label)}}</option></select><label>{{vm.tr('عرض')}}<select v-model.number="size" aria-label="عدد الحسابات في الصفحة"><option v-for="n in [10,25,50,100]" :value="n">{{n}}</option></select></label></div><p class="caption">{{vm.tr('عدد الحسابات المطابقة')}}: {{filtered.length}}</p><div class="tablewrap"><table><thead><tr><th>{{vm.tr('الحساب')}}</th><th>{{vm.tr('النوع')}}</th><th>{{vm.tr('تابع إلى')}}</th><th>{{vm.tr('الرصيد المتاح')}}</th><th>{{vm.tr('الإجراء')}}</th></tr></thead><tbody><tr v-for="a in shown" :key="a.id"><td>{{a.name}}</td><td>{{vm.tr(vm.walletAccountType(a))}}</td><td>{{parent(a)}}</td><td>{{vm.money(vm.walletTableAmount(a.id,service))}} {{vm.tr('د.ع')}}</td><td><button class="btn small" @click="details(a)">{{vm.tr('عرض التفاصيل')}}</button></td></tr><tr v-if="!filtered.length"><td colspan="5" class="empty">{{vm.tr('لا توجد حسابات مطابقة')}}</td></tr></tbody></table></div><div class="table-pagination-footer"><button class="btn small" :disabled="page<=1" @click="page--">{{vm.tr('السابق')}}</button><span>{{vm.tr('الصفحة')}} {{page}} {{vm.tr('من')}} {{pages}}</span><button class="btn small" :disabled="page>=pages" @click="page++">{{vm.tr('التالي')}}</button></div></section>`
};
const accountDetail={computed:{vm(){return this.$root},account(){return this.vm.accounts.find(a=>a.id===this.vm.modal.accountId)},service(){return this.vm.modal.service},parent(){if(!this.account)return '—';const a=this.account,id=this.vm.s.pos.some(p=>p.id===a.id)?a.agent:a.parent;return this.vm.accounts.find(x=>x.id===id)?.name||'—'}},methods:{movements(){if(!this.account)return;const panel=this.vm.$refs.operations;panel.account=this.account.id;panel.tab='balances';this.vm.closeModal();this.$nextTick(()=>document.querySelector('.wallet-movements')?.scrollIntoView({behavior:'smooth'}))}},template:`<div v-if="account"><dl class="account-fields"><div><dt>{{vm.tr('النوع')}}</dt><dd>{{vm.tr(vm.walletAccountType(account))}}</dd></div><div><dt>{{vm.tr('تابع إلى')}}</dt><dd>{{parent}}</dd></div><div><dt>{{vm.tr('المحافظة')}}</dt><dd>{{account.city||'—'}}</dd></div><div><dt>{{vm.tr('الحالة')}}</dt><dd>{{vm.tr(account.active?'مفعّل':'معطّل')}}</dd></div><div><dt>{{vm.tr('الرصيد الحالي')}}</dt><dd>{{vm.money(vm.walletTableAmount(account.id,service,false))}} {{vm.tr('د.ع')}}</dd></div><div><dt>{{vm.tr('الرصيد المتاح')}}</dt><dd>{{vm.money(vm.walletTableAmount(account.id,service))}} {{vm.tr('د.ع')}}</dd></div></dl><div class="formfoot"><button class="btn" @click="vm.closeModal()">{{vm.tr('إغلاق')}}</button><button class="btn primary" @click="movements">{{vm.tr('عرض حركاته')}}</button></div></div><p v-else>{{vm.tr('الحساب غير متاح ضمن نطاقك')}}</p>`};

function total(vm,id,service,available){const ids=service==='all'?['voucher','topup','cash',...vm.s.providers.filter(p=>p.connection==='API').map(p=>'api:'+p.id)]:[service];return ids.reduce((n,s)=>n+vm.engine[available?'serviceAvailable':'serviceBalance'](id,s),0)}
function install(o){
 o.methods.walletTableAmount=function(id,service,available=true){return total(this,id,service,available)};
 o.components["wallet-accounts-table"]=accountTable; o.components["wallet-account-detail"]=accountDetail;
 const data=o.data;o.data=function(){return {...data.call(this),walletFilters:empty()}};
 o.components['wallet-filter-dialog']=dialog;
 o.methods.emptyWalletFilters=empty;o.methods.walletAccountType=function(a){return labels[kind(this,a)]};
 o.computed.walletFiltersActive=function(){return Object.values(this.walletFilters).some(Boolean)};
 o.methods.openWalletFilters=function(){this.modal={kind:'walletFilters',title:'فلترة المحافظ والتحويلات',draft:Masal.clone(this.walletFilters),error:''}};
 o.methods.applyWalletFilters=function(){const f=this.modal.draft;for(const k of ['from','to'])if(f[k]&&(!/^\d{4}-\d{2}-\d{2}$/.test(f[k])||Number.isNaN(Date.parse(f[k])))){this.modal.error='اختر تاريخًا صحيحًا';return}if(f.from&&f.to&&f.from>f.to){this.modal.error='تاريخ البداية يجب أن يسبق تاريخ النهاية';return}if(f.city&&!this.scopeFilterCities.includes(f.city)||f.kind&&!this.scopeFilterKinds.some(k=>k.id===f.kind)){this.modal.error='الاختيار خارج نطاق حسابك';return}if(f.network&&!this.scopeFilterAgents.some(a=>a.id===f.network)||f.account&&!accounts(this,this.accounts,f,true).some(a=>a.id===f.account)){this.modal.error='اختر حسابًا ضمن النتائج المتاحة';return}this.walletFilters=Masal.clone(f);this.dashboardFilter=null;const panel=this.$refs.operations;if(panel){panel.account='';panel.fundSelected=[]}this.closeModal()};
 o.methods.clearWalletFilters=function(){this.walletFilters=empty();this.dashboardFilter=null;const p=this.$refs.operations;if(p){p.account='';p.fundSelected=[]}};
 const change=o.methods.switchUser;o.methods.switchUser=function(...args){this.walletFilters=empty();return change.apply(this,args)};
 o.computed.walletReconciliationAgents=function(){return accounts(this,this.visibleAgents.filter(a=>!a.parent),this.walletFilters)};
 const panel=o.components['operations-panel'];
 panel.components={...panel.components,"wallet-accounts-table":accountTable};
 panel.computed.walletAccounts=function(){return accounts(this.vm,this.accounts,this.vm.walletFilters)};
 panel.computed.cardMetrics=function(){const ids=new Set((this.walletAccounts||[]).map(a=>this.e.main(this.e.accountAgent(a.id))));const cards=this.s.cards.filter(c=>ids.has(c.agent)&&['Available','Reserved','_Held'].includes(c.status));return {count:cards.length,cost:cards.reduce((n,c)=>n+Number(c.cost||0),0),credit:cards.reduce((n,c)=>n+Number(c.credit??c.cost??0),0)}};
 panel.computed.walletAgents=function(){return this.walletAccounts.filter(a=>this.s.agents.some(x=>x.id===a.id))};
 const balance=panel.computed.balanceTotal;panel.computed.balanceTotal=function(){return this.page==='wallets'?this.walletAccounts.reduce((n,a)=>n+this.e.serviceBalance(a.id,this.service),0):balance.call(this)};
 for(const key of ['ledger','requests','transfers','invoices']){const base=panel.computed[key];panel.computed[key]=function(){const rows=base.call(this);if(this.page!=='wallets')return rows;const ids=new Set(this.walletAccounts.map(a=>a.id)),f=this.vm.walletFilters;return rows.filter(r=>(key==='ledger'?ids.has(r.account):key==='invoices'?ids.has(r.agent):ids.has(r.from)||ids.has(r.to))&&(key==='invoices'?this.service==='voucher':!r.service||r.service===this.service)&&record(this.vm,r,f))}}
 // Outstanding debt remains a current total, independent of the displayed date range.
 panel.computed.debt=function(){if(!this.account||!this.vm.visibleAgents.some(a=>a.id===this.account))return 0;return this.s.batchInvoices.filter(i=>i.agent===this.account&&i.status!=='معكوسة').reduce((n,i)=>n+i.amount,0)-this.s.collections.filter(c=>c.account===this.account).reduce((n,c)=>n+c.amount,0)};
}
root.MasalWalletFilters={install};
})(globalThis);
