import {createApp,ref,computed,watch,nextTick,onMounted,onUnmounted} from 'vue/dist/vue.esm-bundler.js'
import {registerSW} from 'virtual:pwa-register'
import {Icon,api,money,date,base,useTheme,currency} from './shared.js'
import './store.css'
import {ProductCard} from './ProductCard.js'
import {appearanceIds,defaultAppearance} from './appearances.js'
import {sceneStyle} from './reference-scenes.js'
registerSW({immediate:true,onRegisteredSW(url,registration){if(registration){console.info('Dananeer PWA registered:',registration.scope);document.documentElement.dataset.pwa='registered'}},onRegisterError(error){console.error('Dananeer PWA registration failed:',error)}})
const uuid=()=>globalThis.crypto?.randomUUID?.()||'demo-'+Date.now()+'-'+Math.random().toString(36).slice(2)
let customer;try{customer=localStorage.getItem('dananeer-customer-v2');if(!customer){customer=uuid();localStorage.setItem('dananeer-customer-v2',customer)}}catch{customer=uuid()}
createApp({components:{Icon,ProductCard},setup(){
const {theme,toggleTheme}=useTheme('store')
const searchOpen=ref(false),searchInput=ref(null)
async function toggleSearch(){searchOpen.value=!searchOpen.value;if(searchOpen.value){await nextTick();searchInput.value?.focus()}}
const data=ref({companies:[],products:[],settings:{}}),page=ref('home'),type=ref('الكل'),companyId=ref('الكل'),search=ref(''),loading=ref(true),error=ref(''),orders=ref([]),notice=ref(''),selected=ref(null),quantity=ref(1),payment=ref('confirm'),payBusy=ref(false),payError=ref(''),receipt=ref(null),requestId=ref(''),installEvent=ref(null),online=ref(navigator.onLine)
const appearancePreview=new URLSearchParams(location.search).get('preview-style');
watch(()=>data.value.settings.appearanceStyle,id=>{document.documentElement.dataset.appearance=appearanceIds.includes(appearancePreview)?appearancePreview:appearanceIds.includes(id)?id:defaultAppearance},{immediate:true});
const buyerCity=ref('');const slideIndex=ref(0),tickets=ref([]),ticketId=ref(''),supportSubject=ref(''),supportMessage=ref(''),supportBusy=ref(false),supportError=ref('');
const appearance=ref(defaultAppearance);
watch(()=>data.value.settings.appearanceStyle,id=>{appearance.value=appearanceIds.includes(appearancePreview)?appearancePreview:appearanceIds.includes(id)?id:defaultAppearance},{immediate:true});
const referenceScene=computed(()=>sceneStyle(appearance.value,theme.value));
const slides=computed(()=>{const enabled=(data.value.settings.slides||[]).filter(s=>s.active!==false);return [...(data.value.settings.referenceHero!==false?[{reference:true,title:'بطاقاتك، أقرب',image:'',link:''}]:[]),...enabled].length?[...(data.value.settings.referenceHero!==false?[{reference:true,title:'بطاقاتك، أقرب',image:'',link:''}]:[]),...enabled]:[{title:data.value.settings.heroTitle||'بطاقاتك، أقرب',description:data.value.settings.heroText||'',image:'',link:''}]});
const collectionId=ref('');
const homeSections=computed(()=>(data.value.settings.sections??[{id:'featured',title:'الأكثر تميزًا',selection:'featured',active:true}]).filter(s=>s.active!==false));
const matchesSection=(p,s)=>!s||s.selection==='all'||s.selection==='featured'&&p.featured||s.selection==='company'&&p.companyId===s.companyId||s.selection==='manual'&&(s.productIds||[]).includes(p.id);
const sortedProducts=computed(()=>data.value.products.slice().sort((a,b)=>(a.sort||0)-(b.sort||0)));
const sectionProducts=(s)=>sortedProducts.value.filter(p=>matchesSection(p,s));
const selectedCollection=computed(()=>homeSections.value.find(s=>s.id===collectionId.value));
function showCollection(id=''){companyId.value='الكل';type.value='الكل';search.value='';go('catalog');collectionId.value=id}

const logoColor=c=>({'آسياسيل':'#ed1737','زين العراق':'#009c75','كورك':'#168bf0'}[c.name]||c.color);
const logoText=c=>({'آسياسيل':'Asiacell','زين العراق':'zain','كورك':'KOREK'}[c.name]||c.name);
const activeSlide=computed(()=>slides.value[slideIndex.value%slides.value.length]);
const activeTicket=computed(()=>tickets.value.find(t=>t.id===ticketId.value));
const ticketStatus=t=>({open:'بانتظار الرد',replied:'تم الرد',closed:'مغلقة'}[t.status]);
async function loadSupport(){try{tickets.value=(await api('my-support',undefined,customer)).tickets}catch(e){supportError.value=e.message}}
async function sendSupport(){if(supportBusy.value)return;supportBusy.value=true;supportError.value='';try{const result=await api('support-send',{id:ticketId.value,subject:supportSubject.value,message:supportMessage.value},customer);ticketId.value=result.id;supportMessage.value='';supportSubject.value='';await loadSupport()}catch(e){supportError.value=e.message}finally{supportBusy.value=false}}
const types=computed(()=>['الكل',...new Set(data.value.companies.map(c=>c.type))]);const company=id=>data.value.companies.find(c=>c.id===id)||{name:'شركة',color:'#6947db',symbol:'D'}
const filtered=computed(()=>data.value.products.filter(p=>matchesSection(p,selectedCollection.value)&&(companyId.value==='الكل'||p.companyId===companyId.value)&&(type.value==='الكل'||company(p.companyId).type===type.value)&&`${p.name} ${p.face} ${company(p.companyId).name}`.toLowerCase().includes(search.value.toLowerCase())))
const visibleProducts=computed(()=>filtered.value.slice().sort((a,b)=>(a.sort||0)-(b.sort||0)))
async function refresh(silent=false){if(!silent)loading.value=true;try{data.value=await api('catalog');error.value=''}catch(e){error.value=e.message}finally{loading.value=false}}
async function loadOrders(){try{orders.value=(await api('my-orders',undefined,customer)).orders}catch(e){notice.value=e.message}}
function go(p){collectionId.value='';page.value=p;if(p==='orders')loadOrders();if(p==='support')loadSupport();window.scrollTo({top:0,behavior:'smooth'})}
function chooseCompany(id){companyId.value=id;type.value='الكل';search.value='';go('catalog')}
function open(p){if(!p.stock)return;selected.value={...p};quantity.value=1;payment.value='confirm';payError.value='';receipt.value=null;requestId.value=uuid()}
async function pay(fail=false){if(payBusy.value)return;payBusy.value=true;payError.value='';payment.value='processing';try{await new Promise(r=>setTimeout(r,850));if(fail){payment.value='failed';return}const result=await api('purchase',{productId:selected.value.id,quantity:Number(quantity.value),expectedPrice:selected.value.price,requestId:requestId.value,city:buyerCity.value},customer);receipt.value=result.order;payment.value='success';await Promise.all([refresh(true),loadOrders()])}catch(e){payError.value=e.message;payment.value='failed'}finally{payBusy.value=false}}
async function copy(code){try{await navigator.clipboard.writeText(code);notice.value='تم نسخ الرمز'}catch{notice.value='حدد الرمز وانسخه يدويًا'}}
function onInstall(e){e.preventDefault();installEvent.value=e}async function install(){if(installEvent.value){await installEvent.value.prompt();installEvent.value=null}else notice.value='اختر إضافة إلى الشاشة الرئيسية من قائمة المتصفح.'}
function connectivity(){online.value=navigator.onLine;if(online.value)refresh(true)}function visibility(){if(!document.hidden){refresh(true);if(page.value==='orders')loadOrders();if(page.value==='support')loadSupport()}}
let timer,slideTimer;onMounted(()=>{refresh();loadOrders();timer=setInterval(()=>{if(!document.hidden&&!payBusy.value){refresh(true);if(page.value==='support')loadSupport()}},8000);slideTimer=setInterval(()=>{if(!document.hidden&&page.value==='home')slideIndex.value=(slideIndex.value+1)%slides.value.length},6000);window.addEventListener('beforeinstallprompt',onInstall);window.addEventListener('online',connectivity);window.addEventListener('offline',connectivity);document.addEventListener('visibilitychange',visibility)})
onUnmounted(()=>{clearInterval(timer);clearInterval(slideTimer);window.removeEventListener('beforeinstallprompt',onInstall);window.removeEventListener('online',connectivity);window.removeEventListener('offline',connectivity);document.removeEventListener('visibilitychange',visibility)})
return{logoColor,logoText,referenceScene,homeSections,sortedProducts,sectionProducts,showCollection,selectedCollection,collectionId,buyerCity,currency,slideIndex,slides,activeSlide,tickets,ticketId,supportSubject,supportMessage,supportBusy,supportError,activeTicket,ticketStatus,sendSupport,searchOpen,searchInput,toggleSearch,theme,toggleTheme,base,data,page,type,companyId,search,loading,error,orders,notice,selected,quantity,payment,payBusy,payError,receipt,online,types,company,filtered,visibleProducts,money,date,refresh,go,chooseCompany,open,pay,copy,install}
},template:`

<div class="app-shell">
<header class="app-header"><a class="brand" @click="go('home')"><img :src="base+'icon-recharge-192.png'" alt="دنارير"><span>دنارير<small>عالمك الرقمي، أقرب.</small></span></a><nav class="desktop-nav"><button :class="{selected:page==='home'}" @click="go('home')">الرئيسية</button><button :class="{selected:page==='catalog'}" @click="go('catalog')">البطاقات</button><button :class="{selected:page==='orders'}" @click="go('orders')">مشترياتي</button></nav><button class="header-search-button" @click="toggleSearch" :aria-expanded="searchOpen" aria-controls="header-search" aria-label="فتح البحث"><Icon name="search"/></button><button class="theme-toggle" @click="toggleTheme" :aria-label="theme==='dark'?'الوضع النهاري':'الوضع الليلي'"><Icon :name="theme==='dark'?'sun':'moon'"/></button><button class="header-profile" @click="go('support')" aria-label="الدعم الفني"><Icon name="support"/></button></header><div v-if="searchOpen" id="header-search" class="header-search-panel"><Icon name="search"/><input ref="searchInput" v-model="search" @input="page='catalog';collectionId=''" @keydown.esc="searchOpen=false" placeholder="ابحث عن بطاقة أو شركة…" aria-label="البحث عن البطاقات"><button @click="searchOpen=false" aria-label="إغلاق البحث"><Icon name="close" size="19"/></button></div>
<main>
<div v-if="!online" class="inline-warning">أنت غير متصل. تحتاج الإنترنت لقراءة المخزون وإتمام الشراء.</div>
<div v-if="error" class="inline-warning">{{error}} <button @click="refresh()">إعادة المحاولة</button></div>
<template v-if="page==='home'||page==='catalog'">

<div v-if="page==='catalog'" class="greeting"><span>كل خياراتك في مكان واحد</span><h1>اكتشف البطاقات</h1></div>

<section v-if="page==='home'" class="campaign" :class="{'reference-campaign':activeSlide.reference,'campaign-with-image':activeSlide.image,'campaign-image-only':activeSlide.image&&!activeSlide.title}"><div v-if="activeSlide.reference" class="reference-scene" :style="referenceScene" aria-hidden="true"></div><button v-if="activeSlide.reference" class="reference-hit" @click="showCollection()" aria-label="اكتشف البطاقات"></button><img v-if="activeSlide.image" class="campaign-image" :src="base+activeSlide.image" :alt="activeSlide.title||'إعلان دنارير'"><div class="campaign-copy" v-if="!activeSlide.reference&&(activeSlide.title||activeSlide.description)"><h2 v-if="activeSlide.title">{{activeSlide.title}}</h2><p v-if="activeSlide.description" class="campaign-description">{{activeSlide.description}}</p><span v-if="activeSlide.link" class="campaign-link-label">عرض الإعلان <Icon name="arrow" size="16"/></span><button v-else @click="showCollection()">اكتشف البطاقات <Icon name="arrow" size="18"/></button></div><a v-if="activeSlide.link" class="campaign-hit" :href="activeSlide.link" :aria-label="activeSlide.title||'فتح الإعلان'"></a><div v-if="!activeSlide.image&&!activeSlide.reference" class="card-scene" aria-hidden="true"><div class="floating-chip"><Icon name="check" size="15"/> بطاقتك جاهزة!</div><div class="visual-card back"><span>DANANEER</span><Icon name="card" size="24"/><b>10,000 <small>IQD</small></b></div><div class="visual-card front"><div><span>DANANEER</span><span>◈</span></div><strong>كل اللي تحتاجه،<br>ببطاقة.</strong><b>5,000 <small>IQD</small></b><div class="card-bars"><i></i><i></i><i></i><i></i><i></i></div></div><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div></div><div v-if="slides.length>1" class="slide-controls"><button v-for="(slide,i) in slides" :class="{active:slideIndex%slides.length===i}" @click="slideIndex=i" :aria-label="'الإعلان '+(i+1)" :aria-pressed="slideIndex%slides.length===i"></button></div></section>
<div v-if="page==='home'" class="trust-row"><span><Icon name="bolt" size="17"/> استلام بلحظتها</span><span><Icon name="shield" size="17"/> محفظة كي</span><span><Icon name="card" size="17"/> خيارات لكل يوم</span></div>
<section v-if="page==='home'" class="companies-section"><div class="section-title"><div><span class="overline">شركاتك المفضلة</span><h2>الشركات</h2></div><button @click="go('catalog');companyId='الكل'">عرض الكل <Icon name="chevron" size="16"/></button></div><div class="company-rail"><button v-for="c in data.companies" :key="c.id" :style="{'--company-brand':c.color}" @click="chooseCompany(c.id)"><div class="company-logo" :style="{'--brand':c.color}"><img v-if="c.logo" :src="base+c.logo" :alt="c.name"><strong v-else class="brand-wordmark" :style="{color:logoColor(c)}">{{logoText(c)}}</strong></div><b>{{c.name}}</b></button></div></section>
<template v-if="page==='home'"><section class="cards-section"><div class="section-title"><h2>البطاقات</h2><button @click="showCollection()">عرض كل البطاقات <Icon name="chevron" size="16"/></button></div><div class="product-rail" role="region" aria-label="البطاقات" tabindex="0"><ProductCard v-for="p in sortedProducts.slice(0,10)" :key="p.id" :product="p" :company="company(p.companyId)" :online="online" @buy="open"/></div></section><section v-for="section in homeSections" :key="section.id" class="cards-section custom-section"><div class="section-title"><h2>{{section.title}}</h2><button @click="showCollection(section.id)">عرض الكل <Icon name="chevron" size="16"/></button></div><div class="product-rail" role="region" :aria-label="section.title" tabindex="0"><ProductCard v-for="p in sectionProducts(section).slice(0,10)" :key="p.id" :product="p" :company="company(p.companyId)" :online="online" @buy="open"/></div><p v-if="!sectionProducts(section).length" class="section-empty">لا توجد بطاقات</p></section></template>
<section v-else class="cards-section"><div class="section-title"><h2>{{selectedCollection?.title||'كل البطاقات'}}</h2><span class="count">{{money(filtered.length)}} بطاقة</span></div><div class="category-pills"><button v-for="t in types" @click="type=t;companyId='الكل'" :class="{active:type===t}">{{t}}</button></div><div class="company-filter"><label>الشركة<select v-model="companyId"><option value="الكل">جميع الشركات</option><option v-for="c in data.companies" :value="c.id">{{c.name}}</option></select></label><button @click="refresh()" aria-label="تحديث البطاقات"><Icon name="refresh" size="18"/></button></div><div v-if="loading&&!data.products.length" class="loading-cards"><div v-for="i in 4" class="skeleton"></div></div><div v-else class="compact-product-grid"><ProductCard v-for="p in visibleProducts" :key="p.id" :product="p" :company="company(p.companyId)" :online="online" @buy="open"/></div><div v-if="!loading&&!visibleProducts.length" class="empty-state"><Icon name="search" size="40"/><h3>ما لقينا بطاقة مطابقة</h3></div></section>
<section v-if="page==='home'" class="install-banner"><div class="install-icon"><Icon name="phone" size="32"/></div><div><h3>دنارير، دائمًا وياك.</h3></div><button @click="install"><Icon name="download" size="17"/> تثبيت التطبيق</button></section>
</template>
<template v-if="page==='orders'"><div class="greeting"><span>كل بطاقاتك محفوظة</span><h1>مشترياتي</h1></div><div v-if="!orders.length" class="empty-state"><Icon name="bag" size="48"/><h3>أول بطاقة بانتظارك</h3><button class="primary" @click="go('catalog')">اكتشف البطاقات</button></div><article class="purchase-card" v-for="o in orders" :key="o.id"><div class="purchase-heading"><div><span class="overline">{{o.company}}</span><h3>{{o.name}} · {{money(o.face)}} د.ع</h3></div><span class="delivered"><Icon name="check" size="14"/> تم التسليم</span></div><div class="purchase-meta"><span>{{date(o.date)}}</span><span dir="ltr">{{o.id}}</span><b>{{money(o.total)}} د.ع</b></div><div class="code-row" v-for="code in o.codes"><code>{{code}}</code><button @click="copy(code)" aria-label="نسخ رمز البطاقة"><Icon name="copy" size="18"/></button></div></article></template>
<template v-if="page==='support'"><div class="greeting"><h1>الدعم الفني</h1></div><div class="support-layout"><section class="support-list"><button class="new-ticket" @click="ticketId='';supportError='';supportMessage=''"><Icon name="plus" size="18"/> رسالة جديدة</button><button v-for="t in tickets" :key="t.id" :class="{active:ticketId===t.id}" @click="ticketId=t.id;supportMessage='';supportError=''"><b>{{t.subject}}</b><small>{{ticketStatus(t)}} · {{date(t.date)}}</small></button></section><section class="support-conversation"><template v-if="activeTicket"><div class="support-heading"><h2>{{activeTicket.subject}}</h2><span class="badge">{{ticketStatus(activeTicket)}}</span></div><div class="messages" aria-live="polite"><article v-for="(m,i) in activeTicket.messages" :key="i" :class="['message',m.sender]"><b>{{m.sender==='support'?'الدعم الفني':'أنت'}}</b><p>{{m.text}}</p><time>{{date(m.date)}}</time></article></div></template><form v-if="!activeTicket||activeTicket.status!=='closed'" @submit.prevent="sendSupport"><label v-if="!activeTicket">عنوان الرسالة<input v-model="supportSubject" required maxlength="100"></label><label>الرسالة<textarea v-model="supportMessage" required maxlength="1500" rows="4"></textarea></label><p v-if="supportError" class="error" role="alert">{{supportError}}</p><button class="primary" :disabled="supportBusy">{{supportBusy?'جارٍ الإرسال…':'إرسال الرسالة'}}<Icon name="arrow" size="18"/></button></form><p v-else class="closed-ticket">المحادثة مغلقة</p></section></div></template>
</main><footer class="store-footer"><span>دنارير <small>كل اللي تحتاجه، أقرب.</small></span></footer>
</div>
<nav class="bottom-nav" :style="{'--tab-index':['home','catalog','orders','support'].indexOf(page)}"><span class="frost-tab-indicator" aria-hidden="true"></span><button v-for="n in [{id:'home',name:'الرئيسية',icon:'home'},{id:'catalog',name:'البطاقات',icon:'card'},{id:'orders',name:'مشترياتي',icon:'bag'},{id:'support',name:'الدعم',icon:'support'}]" :class="{active:page===n.id}" @click="go(n.id)"><span class="nav-icon"><Icon :name="n.icon" size="21"/></span><span>{{n.name}}</span></button></nav>
<div v-if="notice" class="toast" role="status" @click="notice=''">{{notice}}<Icon name="close" size="17"/></div>
<div v-if="selected" class="modal-backdrop" @click.self="!payBusy&&(selected=null)"><section class="checkout" role="dialog" aria-modal="true" aria-label="شراء بطاقة"><button class="modal-close" :disabled="payBusy" @click="selected=null" aria-label="إغلاق"><Icon name="close"/></button><template v-if="payment==='confirm'"><div class="checkout-logo" :style="{'--brand':company(selected.companyId).color}">{{company(selected.companyId).symbol}}</div><span class="overline">{{company(selected.companyId).name}}</span><h2>{{selected.name}} · {{money(selected.face)}} د.ع</h2><div class="quantity-row"><span>الكمية</span><div><button @click="quantity=Math.max(1,quantity-1)" :disabled="quantity===1">−</button><b>{{quantity}}</b><button @click="quantity=Math.min(10,selected.stock,quantity+1)" :disabled="quantity>=Math.min(10,selected.stock)">+</button></div></div><label v-if="selected.allowedCities?.length" class="city-checkout">المحافظة<select v-model="buyerCity" required><option value="">اختر المحافظة</option><option v-for="c in selected.allowedCities">{{c}}</option></select></label><div class="pay-method"><span class="qi-symbol">Qi</span><div><strong>محفظة كي</strong></div><Icon name="check" size="20"/></div><div class="total-row"><span>المبلغ الإجمالي</span><strong>{{money(selected.price*quantity)}} <small>د.ع</small></strong></div><button class="primary full" :disabled="selected.allowedCities?.length&&!buyerCity" @click="pay(false)">تأكيد الشراء <Icon name="arrow" size="18"/></button></template><template v-if="payment==='processing'"><div class="spinner"></div><h2>لحظات، ونجهز بطاقتك.</h2></template><template v-if="payment==='failed'"><div class="result-icon failed"><Icon name="close" size="32"/></div><h2>لم تكتمل العملية</h2><p v-if="payError" class="error" role="alert">{{payError}}</p><button class="primary full" @click="payment='confirm'">حاول مرة أخرى</button></template><template v-if="payment==='success'"><div class="result-icon"><Icon name="check" size="32"/></div><span class="overline">تم الشراء</span><h2>بطاقتك جاهزة!</h2><div class="code-row" v-for="code in receipt.codes"><code>{{code}}</code><button @click="copy(code)" aria-label="نسخ الرمز"><Icon name="copy" size="18"/></button></div><button class="primary full" @click="selected=null;go('orders')">عرض مشترياتي <Icon name="bag" size="18"/></button></template></section></div>
`}).mount('#app')



import './apple.css'



import './store-refinements.css'
import './experience.css'




import './compact-store.css'
import './model-three.css'
import './appearances.css'


import './reference-layout.css'
