export type Row={id:string;module:string;version:number;data:Record<string,string|number>};
export type Field={key:string;label:string;type?:string;options?:string[];optional?:boolean};
export type Module={id:string;title:string;subtitle:string;group:number;fields:Field[];editable?:boolean;action?:string;note?:string;states?:string[]};
const f=(key:string,label:string,type='text',options?:string[],optional=false):Field=>({key,label,type,options,optional});
const name=f('name','الاسم');const agent=f('agent','الوكيل','select',['وكيل بغداد الرئيسي','وكيل أربيل الرئيسي','وكيل البصرة الرئيسي','فرع الكرادة']);const status=f('status','الحالة');
export const modules:Module[]=[
{id:'agents',group:1,title:'الوكلاء',subtitle:'الهيكل التجاري وعلاقات الوكلاء الرئيسيين والفرعيين',editable:true,action:'إضافة وكيل',note:'الوكيل الرئيسي يمتلك مخزنًا مستقلًا. الوكيل الفرعي يمتلك محفظة ويسحب من مخزن الرئيسي.',fields:[name,f('type','نوع الوكيل','select',['Main Agent','Sub-Agent']),f('parent','الوكيل الأعلى'),f('city','المحافظة'),f('phone','الهاتف','tel'),f('supervisor','المشرف المسؤول'),f('status','الحالة','select',['نشط','موقوف']),f('support','معلومات الدعم')]},
{id:'pos',group:2,title:'نقاط البيع والأجهزة',subtitle:'بيانات نقطة البيع وربط الجهاز والموقع الجغرافي',editable:true,action:'إضافة نقطة بيع',note:'لكل نقطة بيع وكيل واحد فقط. حالة الاتصال المعروضة توضيحية؛ الربط بالأجهزة لم يتم بعد.',fields:[name,f('owner','اسم صاحب المحل'),agent,f('city','المحافظة'),f('address','العنوان'),f('phone','الهاتف','tel'),f('email','البريد','email',undefined,true),f('device','نوع الجهاز'),f('serial','Serial Number'),f('deviceId','Device ID'),f('certificate','مرجع Device Certificate'),f('installation','App Installation ID'),f('lat','خط العرض','number'),f('lng','خط الطول','number'),f('status','الحالة','select',['متصل','غير متصل','موقوف']),f('lastSeen','آخر اتصال')]},
{id:'orders',group:3,title:'الطلبيات والاستيراد',subtitle:'دورة الطلبية من المسودة إلى تحميل دفعة البطاقات',editable:true,action:'طلبية جديدة',note:'تُحفظ الطلبيات الجديدة كمسودة. لا تُرفع رموز PIN حقيقية في بيئة المراجعة؛ فحص الملف هنا لعينة معرفات توضيحية فقط.',fields:[name,agent,f('city','المدينة'),f('supplier','الجهة المجهزة · Supplier'),f('provider','المزود · Provider'),f('category','الفئة'),f('type','نوع البطاقة','select',['محلية','عالمية']),f('quantity','عدد البطاقات','number'),f('expiry','تاريخ الانتهاء','date'),f('format','تنسيق الملف','select',['CSV','Excel','TXT']),f('status','الحالة','select',['Draft'])],states:['Draft','Pending Review','Validated','Partially Accepted','Loaded','Partially Used','Completed','Quarantined','Exported','Cancelled by Reversal']},
{id:'inventory',group:3,title:'مخزون البطاقات والدفعات',subtitle:'سجل مخزون البطاقات · الأعداد والحالات والانتهاء',note:'FEFO: الأقرب انتهاءً أولًا. عند تساوي الانتهاء يطبق FIFO: الأقدم إدخالًا أولًا. لا تعرض اللوحة PIN أو CVC.',fields:[name,agent,f('order','الطلبية'),f('category','الفئة'),f('quantity','العدد','number'),f('available','المتاح','number'),f('expiry','تاريخ الانتهاء','date'),status]},
{id:'costs',group:3,title:'تكلفة المخزون',subtitle:'سجل تكلفة المخزون المستقل عن المحافظ',note:'تحميل البطاقات لا ينشئ رصيدًا ماليًا قابلًا للتحويل.',fields:[name,agent,f('quantity','عدد البطاقات','number'),f('unitCost','تكلفة البطاقة · د.ع','number'),f('supplyCost','مصاريف التوريد · د.ع','number'),f('total','إجمالي تكلفة الدفعة · د.ع','number')]},
{id:'providers',group:3,title:'الشركات والمزودون',subtitle:'فصل العلامة التجارية عن الجهة المجهزة',editable:true,action:'إضافة مزود',note:'Operator/Brand هي العلامة؛ Supplier هي الجهة المجهزة؛ دور الاتحاد / الموزع المركزي بانتظار التوثيق.',fields:[name,f('brand','شركة الاتصالات / العلامة'),f('supplier','الجهة المجهزة'),f('connection','نوع الربط','select',['ملفات','API']),f('posImage','صورة POS · رابط','url',undefined,true),f('receiptImage','شعار الوصل · رابط','url',undefined,true),f('status','الحالة','select',['نشط','موقوف','بانتظار الربط'])]},
{id:'categories',group:3,title:'المنتجات والفئات',subtitle:'الفئات المحلية والعالمية وحقول البطاقة',editable:true,action:'إضافة فئة',note:'Provider Serial صادر من المزود؛ Internal Serial معرف داخلي. البطاقات العالمية تدعم حقولًا مرنة وليست ثلاثة أعمدة ثابتة.',fields:[name,f('provider','المزود'),f('value','القيمة الاسمية','number'),f('currency','العملة','select',['IQD','USD']),f('type','النوع','select',['محلية','عالمية']),f('fields','الحقول المطلوبة'),f('position','ترتيب الظهور','number'),f('scope','الوكلاء / المناطق المسموحة'),f('status','الحالة','select',['نشط','موقوف','بدون سعر فعال'])]},
{id:'wallets',group:4,title:'المحافظ والحسابات',subtitle:'سجل المحافظ · المتاح والمحجوز والمستهلك',note:'الأرصدة هنا نموذجية. التحويلات والإيداعات الحقيقية تنتظر اعتماد القواعد المالية والربط المحاسبي.',fields:[name,agent,f('available','الرصيد المتاح · د.ع','number'),f('reserved','المبلغ المحجوز · د.ع','number'),f('consumed','المستهلك · د.ع','number'),f('returns','المرتجعات · د.ع','number'),f('credit','سقف الائتمان'),status]},
{id:'prices',group:4,title:'قوائم الأسعار',subtitle:'Agent Price لكل وكيل وفئة وتاريخ سريان',editable:true,action:'اقتراح سعر',note:'يمنع السعر صفر أو الأقل من الحد الأدنى التعاقدي. تحفظ التغييرات كاقتراح بانتظار مراجع ثانٍ؛ لا تُفعّل أسعار البيع الحقيقي.',fields:[name,agent,f('category','الفئة'),f('city','المحافظة / المنطقة'),f('price','Agent Price · د.ع','number'),f('minimum','الحد الأدنى التعاقدي · د.ع','number'),f('exchange','سعر صرف الدولار','number'),f('effective','تاريخ السريان','date'),f('status','الحالة','select',['بانتظار الاعتماد'])]},
{id:'sales',group:5,title:'المبيعات والطباعة',subtitle:'سجل المبيعات والأرباح وحالة تسليم البطاقة',note:'البيع وكشف PIN والإصدار والإرسال للجهاز ونجاح الطباعة أحداث مستقلة. لا يُنفذ بيع حقيقي في هذه البيئة.',fields:[name,agent,f('pos','نقطة البيع'),f('category','الفئة'),f('quantity','الكمية','number'),f('price','سعر البيع · د.ع','number'),f('cost','تكلفة الشراء · د.ع','number'),f('date','التاريخ','date'),status],states:['Available','Reserved','Issued','Print Requested','Printed','Print Failed','Reprint Requested','Reprinted','Delivered','Quarantined']},
{id:'reprints',group:5,title:'إعادة الطباعة والاستثناءات',subtitle:'متابعة فشل الطباعة وإعادة البطاقة نفسها',note:'إذا كُشف PIN لا تعاد البطاقة إلى المتاح ولا يصدر PIN آخر. تجاوز الحد يحتاج موافقة؛ الإرسال الفعلي للطابعة بانتظار الربط.',fields:[name,agent,f('transaction','رقم العملية'),f('pos','الجهاز / النقطة'),f('reason','سبب إعادة الطباعة'),f('revealed','هل كُشف PIN؟'),f('attempts','عدد المحاولات','number'),f('limit','Reprint Limit','number'),f('employee','الموظف'),f('time','وقت المحاولة'),status]},
{id:'limits',group:5,title:'حدود البيع والطباعة',subtitle:'حدود الكمية والقيمة والتكرار حسب الفئة والوكيل والجهاز',editable:true,action:'إضافة سياسة حدود',note:'هذه إعدادات مقترحة؛ تفعيل الإنفاذ على أجهزة POS يتطلب الربط الإنتاجي. لا تتجاوز حدود المزود.',fields:[name,agent,f('scope','الفئة / مجموعة المزود / الجهاز'),f('transaction','Per Transaction Quantity Limit','number'),f('dailyQty','Daily Quantity Limit','number'),f('dailyAmount','Daily Amount Limit · د.ع','number'),f('reprint','Reprint Limit','number'),f('velocity','Velocity Limit · ثانية','number'),f('walletLimit','Agent Credit/Wallet Limit · د.ع','number')]},
{id:'receipts',group:5,title:'قوالب الوصل',subtitle:'قالب المزود والوكيل وإعدادات الطباعة',editable:true,action:'إضافة قالب',fields:[name,agent,f('provider','المزود / المنتج'),f('header','Header'),f('footer','Footer'),f('width','عرض الورق','select',['58 mm','80 mm']),f('language','لغة الوصل','select',['العربية','کوردی','English']),f('fields','الحقول الظاهرة'),f('image','رابط صورة اختيارية','url',undefined,true)]},
{id:'claims',group:5,title:'البطاقات التالفة والمطالبات',subtitle:'عزل الدفعات ومتابعة جواب الجهة المجهزة',editable:true,action:'تسجيل مطالبة',note:'البطاقات المعلقة ليست خسارة أو استردادًا نهائيًا. التسوية المالية لا تُنفّذ قبل جواب المزود.',fields:[name,agent,f('order','الطلبية / Batch'),f('category','الفئة'),f('quantity','البطاقات المتأثرة','number'),f('reason','سبب المطالبة'),f('status','الحالة','select',['قيد المراجعة','معزولة','بانتظار المزود','مغلقة']),f('result','نتيجة المطالبة','select',['بانتظار الرد','استبدال','إعادة تفعيل','رفض','تعويض','خسارة'])]},
{id:'exports',group:5,title:'تصدير البطاقات الآمن',subtitle:'طلبات تصدير الدفعات المعزولة',editable:true,action:'طلب تصدير',note:'تصدير PIN الحقيقي معطل لحين ربط التشفير والتنزيل محدود الصلاحية. التصدير المتاح للجداول هو بيانات وصفية فقط.',fields:[name,agent,f('batch','Batch'),f('quantity','العدد','number'),f('reason','سبب التصدير'),f('format','التنسيق المطلوب','select',['CSV مشفر','Excel مشفر']),f('status','الحالة','select',['بانتظار الاعتماد'])]},
{id:'tickets',group:6,title:'الدعم الفني',subtitle:'نقطة البيع ← دعم الوكيل ← إدارة النظام',editable:true,action:'تذكرة جديدة',fields:[name,agent,f('requester','مقدم الطلب'),f('description','وصف المشكلة','textarea'),f('priority','الأولوية','select',['عادية','مرتفعة','عاجلة']),f('status','الحالة','select',['مفتوحة','قيد المعالجة','مصعّدة','مغلقة']),f('replies','الردود والمتابعة','textarea',undefined,true),f('attachment','رابط مرفق','url',undefined,true)]},
{id:'notifications',group:6,title:'الإشعارات',subtitle:'مسودات الرسائل ونطاق المستلمين',editable:true,action:'إنشاء مسودة',note:'يحفظ الإشعار كمسودة فقط؛ لا ترسل هذه النسخة رسائل إلى أشخاص أو أجهزة.',fields:[name,f('audience','الجمهور','select',['جميع الأجهزة','وكيل محدد','نقاط بيع وكيل','مجموعة مختارة']),agent,f('message','نص الإشعار','textarea'),f('image','رابط الصورة','url',undefined,true),f('status','الحالة','select',['مسودة'])]},
{id:'alerts',group:6,title:'التنبيهات',subtitle:'الانتهاء والمخزون والطباعة والأجهزة',fields:[name,agent,f('category','الفئة / الجهاز'),f('order','الطلبية'),f('quantity','عدد البطاقات','number'),f('severity','الأهمية'),status]},
{id:'monitoring',group:7,title:'المراقبة',subtitle:'Monitoring · الاتصال والأداء وحالة العمليات',note:'جميع مؤشرات المراقبة نموذجية وليست قياسًا مباشرًا للخوادم أو واجهات API.',fields:[name,f('value','القيمة'),f('threshold','عتبة التنبيه'),f('time','وقت القياس'),status]},
{id:'users',group:8,title:'الهوية والمستخدمون',subtitle:'المستخدمون الداخليون والأدوار ونطاق الوصول',editable:true,action:'إضافة سجل مستخدم',note:'هذه سجلات تعريفية للمراجعة، وليست حسابات دخول فعلية. لا تُدخل كلمات مرور أو رموز استرداد.',fields:[name,f('email','البريد','email'),f('role','الدور','select',['System Owner','Supervisor','Main Agent','Sub-Agent','POS']),f('scope','نطاق الشجرة'),f('mfa','المصادقة الثنائية','select',['إلزامية · TOTP','اختيارية · TOTP']),f('status','الحالة','select',['نشط','موقوف'])]},
{id:'roles',group:8,title:'الصلاحيات ونطاق الشجرة',subtitle:'Hierarchy Scope · الرؤية والصلاحيات الحساسة',note:'هذه مصفوفة مرجعية. المصادقة وتطبيق نطاق كل مستخدم على الخادم مطلوبان قبل فتح النظام للوكلاء.',fields:[name,f('scope','نطاق الرؤية'),f('permissions','الصلاحيات'),f('sensitive','الاعتماد الحساس')]},
{id:'security',group:8,title:'المراقبة والأمان',subtitle:'سياسات الإيقاف والجلسات والمصادقة',editable:true,action:'إضافة سياسة',note:'الإعدادات محفوظة كمقترحات ولا توقف تطبيقات أو أجهزة حقيقية. TOTP إلزامي للحسابات الحساسة؛ إعادة التعيين عبر OTP أو رابط، دون كلمة افتراضية.',fields:[name,f('scope','نطاق التطبيق'),f('value','القيمة المقترحة'),f('reason','السبب'),f('status','الحالة','select',['مقترح','قيد المراجعة'])]},
{id:'integrations',group:9,title:'تكاملات API',subtitle:'Provider Integration → Provider Credentials per Agent → Products',editable:true,action:'إضافة إعداد ربط',note:'بيانات الربط وصفية فقط. Token لا يُعرض ولا يُحفظ هنا. اختبار الاتصال وتدوير المفاتيح ينتظران وثائق API وبيئة آمنة للأسرار.',fields:[name,agent,f('provider','المزود'),f('environment','البيئة','select',['Test','Production']),f('products','المنتجات المسموحة'),f('expiry','انتهاء الاعتماد','date'),f('status','الحالة','select',['بانتظار الوثائق','بانتظار الربط'])]},
{id:'branding',group:9,title:'الهوية البصرية',subtitle:'Multi-Tenant Branding · هوية واحدة مخصصة لكل وكيل',editable:true,action:'إضافة هوية',fields:[name,agent,f('color','اللون الرئيسي','color'),f('logo','رابط الشعار','url',undefined,true),f('theme','الثيم','select',['فاتح','داكن']),f('support','معلومات الدعم'),f('receipt','قالب الوصل')]},
{id:'content',group:9,title:'إدارة صفحة الهبوط',subtitle:'الأخبار والسلايدرات والتواصل وروابط التطبيقات',editable:true,action:'إضافة محتوى',note:'محتوى محفوظ كمسودة. الاسم التجاري النهائي والصفحات القانونية يحتاجان اعتمادًا منفصلًا.',fields:[name,f('type','نوع المحتوى','select',['تعريف المنصة','من نحن','الخدمات','خبر','سلايدر','الدعم والتواصل','رابط تطبيق','صفحة قانونية']),f('language','اللغة','select',['العربية','کوردی','English']),f('body','المحتوى','textarea'),f('link','الرابط','url',undefined,true),f('status','الحالة','select',['مسودة','قيد المراجعة'])]},
];
const pack=(module:string,items:Record<string,string|number>[]):Row[]=>items.map((data,i)=>({id:`${module}-${i+1}`,module,version:1,data}));
export const seed:Row[]=[
...pack('agents',[
{name:'وكيل بغداد الرئيسي',type:'Main Agent',parent:'إدارة النظام / ماسال',city:'بغداد',phone:'نموذج توضيحي',supervisor:'مشرف المنطقة الوسطى',status:'نشط',support:'دعم وكيل بغداد'},
{name:'فرع الكرادة',type:'Sub-Agent',parent:'وكيل بغداد الرئيسي',city:'بغداد',phone:'نموذج توضيحي',supervisor:'مشرف المنطقة الوسطى',status:'نشط',support:'دعم الفرع'},
{name:'وكيل أربيل الرئيسي',type:'Main Agent',parent:'إدارة النظام / ماسال',city:'أربيل',phone:'نموذج توضيحي',supervisor:'مشرف المنطقة الشمالية',status:'نشط',support:'دعم وكيل أربيل'},
{name:'وكيل البصرة الرئيسي',type:'Main Agent',parent:'إدارة النظام / ماسال',city:'البصرة',phone:'نموذج توضيحي',supervisor:'مشرف المنطقة الجنوبية',status:'نشط',support:'دعم وكيل البصرة'}]),
...pack('pos',[['مركز النور','بغداد','فرع الكرادة',33.30,44.43,'متصل'],['مكتبة الرافدين','بغداد','وكيل بغداد الرئيسي',33.34,44.40,'متصل'],['مركز زاكروس','أربيل','وكيل أربيل الرئيسي',36.19,44.01,'متصل'],['اتصالات الفيحاء','البصرة','وكيل البصرة الرئيسي',30.50,47.81,'غير متصل']].map(([name,city,agent,lat,lng,status],i)=>({name,city,agent,lat,lng,status,owner:['أحمد علي','حسن كريم','سردار عمر','علي حسين'][i],phone:'نموذج توضيحي',address:'موقع تقريبي توضيحي',email:'',device:'POS · نموذج',serial:`DEMO-SN-00${i+1}`,deviceId:`DEMO-DEVICE-${i+1}`,certificate:'بانتظار الربط',installation:`DEMO-APP-${i+1}`,lastSeen:'2026-09-09 10:30'}))),
...pack('orders',[['ORD-2026-001','آسياسيل','5,000 د.ع',5000,'2026-09-20','Partially Used'],['ORD-2026-002','زين','10,000 د.ع',3000,'2027-02-01','Loaded'],['ORD-2026-003','كورك','5,000 د.ع',2000,'2027-01-15','Pending Review']].map(([name,provider,category,quantity,expiry,status])=>({name,agent:'وكيل بغداد الرئيسي',city:'بغداد',supplier:'مجهز محلي · نموذج',provider,category,quantity,expiry,status,type:'محلية',format:'CSV'}))),
...pack('inventory',[{name:'BATCH-001',agent:'وكيل بغداد الرئيسي',order:'ORD-2026-001',category:'آسياسيل 5,000',quantity:5000,available:1250,expiry:'2026-09-20',status:'Partially Used'},{name:'BATCH-002',agent:'وكيل بغداد الرئيسي',order:'ORD-2026-002',category:'زين 10,000',quantity:3000,available:3000,expiry:'2027-02-01',status:'Loaded'},{name:'BATCH-003',agent:'وكيل أربيل الرئيسي',order:'ORD-DEMO-003',category:'كورك 5,000',quantity:1200,available:0,expiry:'2027-01-15',status:'Quarantined'}]),
...pack('costs',[{name:'BATCH-001',agent:'وكيل بغداد الرئيسي',quantity:5000,unitCost:4700,supplyCost:0,total:23500000},{name:'BATCH-002',agent:'وكيل بغداد الرئيسي',quantity:3000,unitCost:9400,supplyCost:0,total:28200000}]),
...pack('providers',['آسياسيل','زين','كورك','الرابعة','Steam'].map((name,i)=>({name,brand:name,supplier:i<3?'مجهز محلي · نموذج':'مزود API · نموذج',connection:i<3?'ملفات':'API',status:i<3?'نشط':'بانتظار الربط',posImage:'',receiptImage:''}))),
...pack('categories',[{name:'آسياسيل 5,000',provider:'آسياسيل',value:5000,currency:'IQD',type:'محلية',fields:'Provider Serial, PIN, Expiry Date',position:1,scope:'بغداد',status:'نشط'},{name:'زين 10,000',provider:'زين',value:10000,currency:'IQD',type:'محلية',fields:'Provider Serial, PIN, Expiry Date',position:2,scope:'جميع الوكلاء',status:'نشط'},{name:'كورك 5,000',provider:'كورك',value:5000,currency:'IQD',type:'محلية',fields:'Internal Serial, PIN, Expiry Date',position:3,scope:'بغداد',status:'بدون سعر فعال'},{name:'بطاقة عالمية · 20 USD',provider:'مزود عالمي',value:20,currency:'USD',type:'عالمية',fields:'Serial, PIN, Expiry Date, CVC, Reference',position:4,scope:'حسب التعاقد',status:'موقوف'}]),
...pack('wallets',[['وكيل بغداد الرئيسي',12000000,250000,4300000],['فرع الكرادة',1500000,50000,1200000],['وكيل أربيل الرئيسي',8400000,0,3200000],['وكيل البصرة الرئيسي',6200000,100000,2600000]].map(([name,available,reserved,consumed])=>({name,agent:name,available,reserved,consumed,returns:0,credit:'بانتظار اعتماد السياسة',status:'نشط'}))),
...pack('prices',[{name:'PRC-001',agent:'وكيل بغداد الرئيسي',category:'آسياسيل 5,000',city:'بغداد',price:5000,minimum:4800,exchange:1300,effective:'2026-09-01',status:'فعال'},{name:'PRC-002',agent:'وكيل بغداد الرئيسي',category:'زين 10,000',city:'بغداد',price:10000,minimum:9600,exchange:1300,effective:'2026-09-01',status:'فعال'}]),
...pack('sales',Array.from({length:14},(_,i)=>({name:`TX-2026-${String(i+1).padStart(4,'0')}`,agent:i%3===0?'وكيل أربيل الرئيسي':'وكيل بغداد الرئيسي',pos:i%3===0?'مركز زاكروس':'مركز النور',category:i%2?'زين 10,000':'آسياسيل 5,000',quantity:1+(i%3),price:i%2?10000:5000,cost:i%2?9400:4700,date:`2026-09-${String(3+Math.floor(i/2)).padStart(2,'0')}`,status:i===13?'Print Failed':'Printed'}))),
...pack('reprints',[{name:'RPT-001',agent:'وكيل بغداد الرئيسي',transaction:'TX-2026-0014',pos:'مركز النور',reason:'نفاد الورق بعد إصدار البطاقة',revealed:'نعم · أرسل للجهاز',attempts:1,limit:5,employee:'موظف نقطة البيع',time:'2026-09-09 10:24',status:'Print Failed'}]),
...pack('limits',[{name:'السياسة النموذجية',agent:'وكيل بغداد الرئيسي',scope:'الفئات المحلية',transaction:5,dailyQty:100,dailyAmount:500000,reprint:5,velocity:3,walletLimit:1000000}]),
...pack('receipts',[{name:'وصل البطاقات المحلية',agent:'وكيل بغداد الرئيسي',provider:'آسياسيل',header:'وكيل بغداد الرئيسي',footer:'شكرًا لزيارتكم',width:'58 mm',language:'العربية',fields:'Provider Serial, PIN, Expiry Date, Transaction, POS, Reprint',image:''}]),
...pack('claims',[{name:'CLM-001',agent:'وكيل أربيل الرئيسي',order:'BATCH-003',category:'كورك 5,000',quantity:1200,reason:'دفعة قيد التحقيق',status:'معزولة',result:'بانتظار الرد'}]),
...pack('exports',[{name:'EXP-001',agent:'وكيل أربيل الرئيسي',batch:'BATCH-003',quantity:1200,reason:'مراجعة الدفعة مع المجهز',format:'CSV مشفر',status:'بانتظار الاعتماد'}]),
...pack('tickets',[{name:'تعذر طباعة البطاقة',agent:'وكيل بغداد الرئيسي',requester:'مركز النور',description:'نفاد الورق بعد إرسال البطاقة. نحتاج مراجعة إعادة طباعة البطاقة نفسها.',priority:'مرتفعة',status:'مفتوحة',replies:'دعم الوكيل: يرجى التحقق من الورق قبل إعادة المحاولة.',attachment:''},{name:'استفسار حول دفعة معزولة',agent:'وكيل أربيل الرئيسي',requester:'الوكيل الرئيسي',description:'متابعة مطالبة BATCH-003 مع الجهة المجهزة.',priority:'عادية',status:'قيد المعالجة',replies:'',attachment:''}]),
...pack('notifications',[{name:'صيانة مجدولة · مسودة',audience:'جميع الأجهزة',agent:'وكيل بغداد الرئيسي',message:'سيتم تحديد موعد الصيانة بعد الاعتماد.',image:'',status:'مسودة'}]),
...pack('alerts',[{name:'دفعة تقترب من الانتهاء',agent:'وكيل بغداد الرئيسي',category:'آسياسيل 5,000',order:'ORD-2026-001',quantity:1250,severity:'مرتفعة',status:'مفتوح'},{name:'فئة بدون سعر فعال',agent:'وكيل بغداد الرئيسي',category:'كورك 5,000',order:'—',quantity:0,severity:'حرجة',status:'البيع محظور'},{name:'فشل طباعة بعد إصدار البطاقة',agent:'وكيل بغداد الرئيسي',category:'مركز النور',order:'TX-2026-0014',quantity:2,severity:'مرتفعة',status:'مراجعة إعادة الطباعة'}]),
...pack('monitoring',[['المستخدمون المتصلون','12','حسب السعة'],['نقاط البيع المتصلة','3 من 4','أقل من 80%'],['معدل الطلبات','24 طلب / دقيقة','أكثر من 200'],['زمن الاستجابة','180 ms','أكثر من 500 ms'],['فشل الطباعة','1','أكثر من 0'],['عمليات معلقة','0','أكثر من 5'],['ضغط قاعدة البيانات','12%','أكثر من 80%'],['محاولات دخول فاشلة','0','أكثر من 5'],['Spam','0','أكثر من 10'],['استهلاك الخوادم','18%','أكثر من 80%'],['API الخارجية','بانتظار الربط','فشل الاتصال']].map(([name,value,threshold])=>({name,value,threshold,time:'عينة 2026-09-09',status:'بيانات نموذجية'}))),
...pack('users',[{name:'مدير النظام',email:'owner@example.com',role:'System Owner',scope:'جميع الوكلاء',mfa:'إلزامية · TOTP',status:'نشط'},{name:'مشرف المنطقة الوسطى',email:'supervisor@example.com',role:'Supervisor',scope:'وكيل بغداد الرئيسي وأبناؤه',mfa:'إلزامية · TOTP',status:'نشط'}]),
...pack('roles',[['System Owner','جميع الوكلاء','إدارة المنصة والصلاحيات والأمان','التصدير والعمليات الحساسة'],['Supervisor','الوكلاء المكلف بهم فقط','الطلبات والأسعار والدعم ضمن التفويض','وفق الصلاحيات الصريحة'],['Main Agent','الوكيل وأبناؤه','المخزن والأسعار وتمويل الفرعي والنقاط','رفع الطلبات حسب التفويض'],['Sub-Agent','نفسه ونقاطه فقط','المحفظة وتمويل النقاط دون مخزن مستقل','لا يرى فروعًا أخرى'],['POS','نقطة البيع فقط','البيع والطباعة وإعادة الطباعة ضمن الحدود','تجاوز حد إعادة الطباعة']].map(([name,scope,permissions,sensitive])=>({name,scope,permissions,sensitive}))),
...pack('security',[['المصادقة الثنائية','الحسابات الحساسة','TOTP إلزامي'],['مدة خمول الجلسة','المستخدمون','60 دقيقة · مقترح'],['إيقاف البيع','المنصة / وكيل / مزود / فئة','غير مفعل'],['إيقاف الطباعة','المنصة / الجهاز','غير مفعل'],['إيقاف التطبيق','جميع الأجهزة','غير مفعل'],['إيقاف تسجيل الوكلاء','التسجيل','غير مفعل'],['إيقاف تسجيل الدخول','المصادقة','غير مفعل'],['تسجيل الخروج عن بعد','جميع أجهزة وكيل / جهاز محدد','بانتظار الربط'],['الحد الأدنى لإصدار التطبيق','أجهزة POS','بانتظار المواصفات'],['قائمة سماح / حظر IP','الشبكات','بانتظار الاعتماد'],['Rate Limiting والقفل المؤقت','تسجيل الدخول','5 محاولات · مقترح'],['مدة تنبيه الانتهاء','الدفعات','30 يومًا · مقترح'],['مدة الاحتفاظ بسجل التدقيق','السجلات','بانتظار الاتفاق']].map(([name,scope,value])=>({name,scope,value,reason:'سياسة مقترحة وفق المرجع التحليلي',status:'مقترح'}))),
...pack('integrations',[{name:'ربط الرابعة',agent:'وكيل بغداد الرئيسي',provider:'الرابعة',environment:'Test',products:'حسب تعاقد الوكيل',expiry:'2027-01-01',status:'بانتظار الوثائق'}]),
...pack('branding',[{name:'هوية وكيل بغداد',agent:'وكيل بغداد الرئيسي',color:'#087f70',logo:'',theme:'فاتح',support:'دعم وكيل بغداد',receipt:'وصل البطاقات المحلية'}]),
...pack('content',[{name:'نبذة عن المنصة',type:'تعريف المنصة',language:'العربية',body:'منصة إدارة بيع البطاقات الإلكترونية وشبكة الوكلاء ونقاط البيع.',link:'',status:'مسودة'}])
];
export const labels:Record<string,string>={Draft:'مسودة', 'Pending Review':'بانتظار المراجعة',Validated:'تم التحقق','Partially Accepted':'مقبولة جزئيًا',Loaded:'محمّلة','Partially Used':'مستخدمة جزئيًا',Completed:'مكتملة',Quarantined:'معزولة',Exported:'مصدّرة','Cancelled by Reversal':'ملغاة بقيد عكسي',Available:'متاحة',Reserved:'محجوزة',Issued:'صادرة','Print Requested':'طُلبت الطباعة',Printed:'مطبوعة','Print Failed':'فشلت الطباعة','Reprint Requested':'طلب إعادة طباعة',Reprinted:'أعيدت طباعتها',Delivered:'مسلّمة','Main Agent':'وكيل رئيسي','Sub-Agent':'وكيل فرعي'};
export function validateRecord(moduleId:string,raw:unknown){const mod=modules.find(m=>m.id===moduleId);if(!mod?.editable)throw Error('هذه الوحدة للعرض فقط');if(!raw||typeof raw!=='object'||Array.isArray(raw))throw Error('البيانات غير صالحة');const input=raw as Record<string,unknown>;const data:Record<string,string|number>={};for(const field of mod.fields){const v=input[field.key];if((v===undefined||v==='')&&field.optional){data[field.key]='';continue}if(v===undefined||v===null||!['string','number'].includes(typeof v)||String(v).trim()==='')throw Error(`الحقل مطلوب: ${field.label}`);if(String(v).length>5000)throw Error('النص يتجاوز الحد المسموح');if(field.type==='number'){if(!Number.isFinite(Number(v))||Number(v)<0)throw Error(`قيمة غير صالحة: ${field.label}`);data[field.key]=Number(v)}else data[field.key]=String(v).trim();if(field.options&&field.key!=='agent'&&!field.options.includes(String(v)))throw Error(`اختر قيمة معتمدة: ${field.label}`);if(field.type==='date'&&!/^\d{4}-\d{2}-\d{2}$/.test(String(v)))throw Error('التاريخ غير صالح');if(field.type==='email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(v)))throw Error('البريد غير صالح');if(field.type==='url'&&!/^https?:\/\//.test(String(v)))throw Error('الرابط يجب أن يبدأ بـ https:// أو http://');if(field.type==='color'&&!/^#[0-9a-f]{6}$/i.test(String(v)))throw Error('اللون غير صالح')}
if(moduleId==='prices'&&(Number(data.price)<=0||Number(data.price)<Number(data.minimum)))throw Error('السعر يجب أن يكون أكبر من صفر وألا يقل عن الحد الأدنى التعاقدي');if(moduleId==='pos'&&(Number(data.lat)>90||Number(data.lng)>180))throw Error('الإحداثيات خارج النطاق');if(moduleId==='orders'&&(!Number.isInteger(data.quantity)||Number(data.quantity)<=0))throw Error('عدد البطاقات يجب أن يكون عددًا صحيحًا موجبًا');return data;}

