/* Creates a standalone, fully offline HTML from the editable Vue application. */
const fs=require('node:fs'),path=require('node:path');
process.chdir(path.resolve(__dirname,'..'));
const mapCountries=JSON.parse(fs.readFileSync('assets/map-countries.geojson','utf8'));
const mapPlaces=JSON.parse(fs.readFileSync('assets/map-places.geojson','utf8'));
fs.writeFileSync('assets/map-places.js','globalThis.MasalMapPlaces='+JSON.stringify({type:'FeatureCollection',features:mapPlaces.features.map(f=>({type:'Feature',properties:{name:f.properties.NAME_AR||f.properties.NAME},geometry:f.geometry}))})+';');
fs.writeFileSync('assets/map-countries.js','globalThis.MasalMapCountries='+JSON.stringify({type:'FeatureCollection',features:mapCountries.features.map(f=>({type:'Feature',properties:{name:f.properties.NAME_AR||f.properties.NAME,id:f.properties.ADM0_A3},geometry:f.geometry}))})+';');
fs.writeFileSync('src/js/company-public-runtime.js','globalThis.MasalCompanyVueSource='+JSON.stringify(fs.readFileSync('assets/vue.global.prod.js','utf8'))+';');
let html=fs.readFileSync('src/runtime/standalone-shell.html','utf8');
const template=require('@vue/compiler-sfc').parse(fs.readFileSync('src/App.vue','utf8')).descriptor.template.content;
html=html.replace('<div id="app"></div>',()=>template);
html=html.replace('<input type="text" dir="ltr" readonly :value="networkLinkedAccount.email||tr(\'غير مسجل\')" aria-label="بريد تسجيل الدخول">','<input type="text" dir="ltr" v-model="networkLogin.email" required autocomplete="username" aria-label="بريد أو اسم مستخدم تسجيل الدخول">');
html=html.replace('<link rel="stylesheet" href="src/css/support-chat.css">','<style>'+fs.readFileSync('src/css/support-chat.css','utf8')+'</style>');
html=html.replace('<link rel="stylesheet" href="src/css/agent-products.css">','<style>'+fs.readFileSync('src/css/agent-products.css','utf8')+'</style>');
html=html.replace('<link rel="stylesheet" href="src/css/representatives.css">','<style>'+fs.readFileSync('src/css/representatives.css','utf8')+'</style>');
html=html.replace('<link rel="stylesheet" href="src/css/network-tree.css">','');
html=html.replace('<link rel="stylesheet" href="src/css/operations.css">','');
html=html.replace('<link rel="stylesheet" href="src/css/reference-identity.css">','');
html=html.replace('<link rel="stylesheet" href="src/css/company-profile.css">','');
html=html.replace('<link rel="stylesheet" href="assets/leaflet.css">','');let css=fs.readFileSync('assets/leaflet.css','utf8')+'\n'+fs.readFileSync('src/css/styles.css','utf8')+'\n'+fs.readFileSync('src/css/operations.css','utf8')+'\n'+fs.readFileSync('src/css/theme.css','utf8')+'\n'+fs.readFileSync('src/css/layout.css','utf8')+'\n'+fs.readFileSync('src/css/polish.css','utf8')+'\n'+fs.readFileSync('src/css/management.css','utf8')+'\n'+fs.readFileSync('src/css/network-tree.css','utf8')+'\n'+fs.readFileSync('src/css/reference-identity.css','utf8')+'\n'+fs.readFileSync('src/css/company-profile.css','utf8')+'\n'+fs.readFileSync('src/css/representatives.css','utf8');
html=html.replace('<link rel="stylesheet" href="src/css/management.css">','');
html=html.replace('<link rel="stylesheet" href="src/css/theme.css">','').replace('<link rel="stylesheet" href="src/css/layout.css">','').replace('<link rel="stylesheet" href="src/css/polish.css">','');
for(const file of ['cairo-regular.ttf','cairo-bold.ttf','cairo-black.ttf','jetbrains-mono.ttf'])css=css.replaceAll('../../assets/'+file,'data:font/ttf;base64,'+fs.readFileSync('assets/'+file).toString('base64'));
html=html.replace('<link rel="stylesheet" href="src/css/styles.css">','<style>'+css+'</style>');
for(const file of ['assets/leaflet.js','assets/map-countries.js','assets/map-places.js','assets/vue.global.prod.js','src/js/access.js','src/js/card-fields.js','src/js/engine.js','src/js/operations-engine.js','src/js/import-reader.js','src/js/operations-ui.js','src/js/workflow-engine.js','src/js/workflow-ui.js','src/js/completion-engine.js','src/js/completion-ui.js','src/js/locales.js','src/js/management-locales.js','src/js/operations-locales.js','src/js/completion-locales.js','src/js/reports.js','src/js/enhancements.js','src/js/staff-model.js','src/js/staff-ui.js','src/js/network-tree.js','src/js/audit-details.js','src/js/network-accounts.js','src/js/support-routing.js','src/js/simple-notifications.js','src/js/form-lifecycle.js','src/js/login-screen.js','src/js/visual-cleanup.js','src/js/excel-export.js','src/js/feature-updates.js','src/js/dashboard.js','src/js/meeting-rules.js','src/js/meeting-ui.js','src/js/categories-ui.js','src/js/regions.js','src/js/company-public-runtime.js','src/js/company-site.js','src/js/card-layout.js','src/js/providers-ui.js','src/js/inventory-ui.js','src/js/catalog-filters.js','src/js/wallet-filters.js','src/js/searchable-selects.js','src/js/cash-orders.js','src/js/table-pagination.js','src/js/seller-accounts.js','src/js/print-escalation.js','src/js/funding-rules.js','src/js/audit-fixes.js','src/js/report-groups.js','src/js/scope-filters.js','src/js/money-inputs.js','src/js/security-controls.js','src/js/simple-wallets.js','src/js/activity-notifications.js','src/js/print-policies.js','src/js/print-policy-scopes.js','src/js/print-scope-picker.js','src/js/account-time-controls.js','src/js/support-broadcast.js','src/js/user-map.js','src/js/price-editor.js','src/js/agent-products.js','src/js/daily-print.js','src/js/support-chat.js','src/js/network-archive.js','src/js/password-admin.js','src/js/pos-register.js','src/js/order-sources.js','src/js/order-parser.js','src/js/multi-orders.js','src/js/inventory-management.js','src/js/ui-localization.js','src/js/representatives-ui.js','src/js/state-storage.js','src/js/app.js']){const source=fs.readFileSync(file,'utf8').replace(/<\/script/gi,'<\\/script');html=html.replace('<script src="'+file+'"></script>',()=>'<script>'+source+'</script>');}
fs.writeFileSync('masal.html',html,'utf8');console.log('Built standalone masal.html ('+Math.round(Buffer.byteLength(html)/1024)+' KB)');
